### ISSUE TITLE
Disable date guessing on CSV

### ISSUE THREAD

**Issue by olafveerman** [energy-data/energydata.info#1]
On CSV upload, `datapusher` and `messytables` try to guess the data types of each column. The date guessing is very aggressive, turning `00:10` into a proper datetime object with the date of upload: `2016-09-12T00:10:00`.

To prevent this from happening, we should temporarily disable date guessing.

**Comment by olafveerman** [comment]
This was solved.

**Comment by yanntanvez** [comment]
Olaf - Clara re-uploaded the Pakistan data yesterday and is having the same issue. Could we please debug ASAP. This is really problematic and preventing a larger data upload to move forward. Many thanks, Yann

**Comment by olafveerman** [comment]
@yanntanvez This is now resolved:

![image](https://cloud.githubusercontent.com/assets/751330/19395972/7f71b440-920e-11e6-8d58-feb06290c08f.png)
