### ISSUE TITLE
Changes to available licenses

### ISSUE THREAD

**Issue by carderne** [energy-data/energydata.info#101]
Add the [World Bank Open Data Terms of Use](http://data.worldbank.org/summary-terms-of-use) to the list of licenses (near the top if possible).

**Comment by olafveerman** [comment]
@carderne 
In the process, should we remove any option from this list? For example: `License not specified` and `Other (Not open)`

**Comment by carderne** [comment]
I think you can leave it as is, there's no harm in having the options there as a catch-all.

**Comment by olafveerman** [comment]
@carderne 
Once we deploy this, it will read the licenses from another repo: https://github.com/energy-data/energydata-licenses
This should make it easier to maintain the list of available licenses.

**Comment by carderne** [comment]
Great!
