### ISSUE TITLE
TimeoutError: QueuePool limit

### ISSUE THREAD

**Issue by carderne** [energy-data/energydata.info#102]
I deleted three datasets and got a Server Error on each.

See error message here:
[server error.pdf](https://github.com/energy-data/energydata.info/files/777470/server.error.pdf)

**Comment by carderne** [comment]
duplicate of #100

**Comment by olafveerman** [comment]
@Naigege @carderne Just did a quick reboot of the server, can you check if it works now?

Regardless of whether the reboot fixes the issue, we should investigate the underlying cause. This seems due to a db connection limit: `TimeoutError: QueuePool limit of size 5 overflow 10 reached.`

@kamicut

**Comment by Naigege** [comment]
@olafveerman it works now. But please also look into the issue to prevent it from happening again. Thanks!

**Comment by Naigege** [comment]
@olafveerman This issue (or a different issue) happens again. I change the dataset name and edit the URL, save changes (have all mandatory fields) and see the server error page. Later I click on the dataset page, the new name shows up, but "404 not found" as the URL is changed. 

If I manually modify the URL to the previous one, the dataset comes up again. If seems the name and URL are changed on the website side, but not in the database.

**Comment by Naigege** [comment]
@olafveerman  Will delete big geojson files to release memory and avoid Timeout error.

**Comment by olafveerman** [comment]
These haven't occurred in quite a while and should be prevented by implementing a file size limit on GeoJSON files. (#82)
