### ISSUE TITLE
GeoJSON preview error again 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#103]
@olafveerman The preview is broken on frontpage and dataset page. Could you have a look at it please? Is it caused by the same issue with #100 #102 ?
![image](https://cloud.githubusercontent.com/assets/6911487/22981619/eb1c2226-f36a-11e6-8001-cc141fc93883.png)
![image](https://cloud.githubusercontent.com/assets/6911487/22981648/f89836c4-f36a-11e6-9e75-6531995fd334.png)

**Comment by olafveerman** [comment]
No, this is a different issue. I'll look into it.

**Comment by olafveerman** [comment]
The token that was provided previously is not working anymore.

**Comment by Naigege** [comment]
@olafveerman The token is the same, but there is some payment issue between GSD and mapbox. It should be resolved by this Friday latest.

**Comment by Naigege** [comment]
@olafveerman it is fixed now.
