### ISSUE TITLE
New metadata scheme

### ISSUE THREAD

**Issue by carderne** [energy-data/energydata.info#105]
See the updated metedata scheme:
[energydata Metadata_20170215.xlsx](https://github.com/energy-data/energydata.info/files/777879/energydata.Metadata_20170215.xlsx)

A few notes:
1. All of the mandatory fields must be completed to continue (and add a red asterisk or something to indicate)
2. Data Type can default to Geospatial
3. Topics should be a lookup field allowing at least 1, at most 3 topics
4. At least one of Country _or_ Region should be entered, but both is allowed
5. Published Year: validate so just a year is entered (i.e. restrict to four digits between 1xxx - 2xxx)

So from the current dataset creation page, the following can be removed: Version, Maintainer, Maintainer Email, Custom Fields

**Comment by olafveerman** [comment]
Closing in favor of #71
