### ISSUE TITLE
Download csv & xlsx file name changed 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#109]
@olafveerman One platform user uploads the csv and xlsx files to the platform <https://energydata.info/dataset/zambia-wind-measurement-data/resource/5ba046c5-be8b-4f0a-bf93-6ece5eeae754>. But when another user downloads it again from the platform, the file name is changed to a strange name: o03public2projets1.-en-cours1702833-10003564---esmap---zambia22.-rp-and-data-transmittalchankaw.xlsx

The user suspects the downloaded file name contains the server path. But it does not happen to the other files I upload. 

Below is the download pop page on firefox:
<img width="444" alt="screenshot 2017-02-20 19 14 00" src="https://cloud.githubusercontent.com/assets/6911487/23146023/0fc49f92-f7a1-11e6-9a3c-f59aaa5a7843.png">

**Comment by Naigege** [comment]
Update from the user: "the platform seems to automatically change the name to the filename path in my computer".

Hope this is useful!

**Comment by Naigege** [comment]
@olafveerman could you have a look on it please?

**Comment by olafveerman** [comment]
@Naigege 
Could you provide me with the original file? Did they upload this through the API, or through the site?

**Comment by Naigege** [comment]
@olafveerman One email with all the original files are just sent. They upload through website, from the local laptop.

**Comment by olafveerman** [comment]
Tried to replicate this with @Naigege , but we were not able to.
Closing for now. @Naigege will check with the user and see if it can be replicated.
