### ISSUE TITLE
Cannot download the file - "Resource data not found" 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#110]
The existing csv file at <https://energydata.info/dataset/vietnam-wind-measurements-giz/resource/cc46c65b-c6b3-42ee-9fff-acbd7685e418> cannot be previewed and downloaded.

<img width="985" alt="screenshot 2017-02-21 10 48 07" src="https://cloud.githubusercontent.com/assets/6911487/23172276/463dc13e-f823-11e6-9991-a0ce46e6e753.png">
<img width="1024" alt="screenshot 2017-02-21 10 48 13" src="https://cloud.githubusercontent.com/assets/6911487/23172281/47ad1506-f823-11e6-831f-7dbd91e8f450.png">

**Comment by Naigege** [comment]
There is another GIZ dataset having the similar download error - <https://energydata.info/dataset/transmission-lines-2016-operational/resource/dbc30e3a-e0b7-416e-b66e-0147f1703128>

It returns the message - {"processingTime":"0 seconds","status":"Failed","error":{"message":"Failed while trying to get item information","code":400,"request":"https://www.arcgis.com/sharing/rest/content/items/ac04d9e3f8e64058b2d61483a3c1f18f?f=json","response":"Item does not exist or is inaccessible.","timestamp":"2017-02-22T21:32:18.222Z"}}.

There is something wrong with the "data harvester"?

**Comment by olafveerman** [comment]
This dataset is not available on the harvested data portal.

The GIZ harvest job was set up to be manual. We should run this periodically to avoid this situation in the future.

**Comment by Naigege** [comment]
The vietnam dataset is uploaded by users. 
But Uganda GIZ dataset has error in fetching source - link <https://energydata.info/dataset/transmission-lines-2016-operational/resource/dbc30e3a-e0b7-416e-b66e-0147f1703128>.

**Comment by Naigege** [comment]
@olafveerman the GIZ dataset is still not linked. Could you set up the harvestor to check sources more frequently? Thanks!

**Comment by Naigege** [comment]
@olafveerman We will manually check all the dataset, so do need to run harvester for now.

**Comment by olafveerman** [comment]
Great, marking this as closed.
