### ISSUE TITLE
List data resources as they are added

### ISSUE THREAD

**Issue by carderne** [energy-data/energydata.info#111]
How easy would this be?

**Comment by olafveerman** [comment]
@carderne Do you mean in the order that they are added?

**Comment by carderne** [comment]
@olafveerman Sorry I should have explained better. While adding resources to a new dataset, it would be nice if they appeared in a list somewhere on _that_ page, so you can keep track of what you have already added. Does that make sense?

**Comment by Naigege** [comment]
Closed for now, may revisit in the future
