### ISSUE TITLE
GeoJSON preview Issue for Zambia Transmission Networks

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#117]
@olafveerman The two GeoJSON are not able to be previewed against base map. It only shows the code. The original files uploaded by partner looks good in QGIS, and projection is right - WGS84. 

The datasets link <https://energydata.info/dataset/transmission-network-zambia>

Could you have a look at it ASAP? Thanks!

**Comment by olafveerman** [comment]
@Naigege 

The resource was generated with two types of previews:

![image](https://cloud.githubusercontent.com/assets/751330/23516058/17cbd5e8-ff3a-11e6-868b-2dee42d47fec.png)

The default view was set to text. I changed the order of the preview by following these steps on the [resource page](https://energydata.info/dataset/transmission-network-zambia/resource/27010457-a07b-4e68-8e21-bd114cda7c77):

1. click Manage
2. click Views
3. click Reorder resource view
4. Drag the 'View' icon to the top

**Comment by Naigege** [comment]
@olafveerman Thanks a lot! I did not notice this feature before.
