### ISSUE TITLE
GeoJSON preview issue on different browser 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#119]
@olafveerman The preview is not working consistently with different browser. It may depends on machine OS and browser version. Could you check more on it and make sure preview can work with different browser please? 

One important user has troubles previewing this dataset https://energydata.info/dataset/nepal-electricity-transmission-network-2013/resource/a4415bff-5649-4f77-b125-5daadb9782ca on IE explorer and firefox. Thanks! 

![ie](https://cloud.githubusercontent.com/assets/6911487/23516452/3a7a7364-ff3b-11e6-8240-cb12107e1801.jpg)

**Comment by olafveerman** [comment]
@Naigege Could you upload the screenshot again?

**Comment by olafveerman** [comment]
@Naigege 
It would be helpful to describe what happens. Are they able to see the basemap and nothing else?

Also, it would be great if you have the opportunity to go into the Developer Tools (F12) and check if there are any errors in the console.

**Comment by Naigege** [comment]
@olafveerman I do not have a firefox here. But I will check the laptop with problems later and update with you.

**Comment by Naigege** [comment]
@olafveerman Firefox does not show the background map, And it has ReferenceError & TypeError as below: 
![firefox](https://cloud.githubusercontent.com/assets/6911487/23522118/cdb61c8c-ff4f-11e6-9c37-b55f410b77e9.png)

**Comment by Naigege** [comment]
@olafveerman Here is what I see on one Mac chrome (with latest version). No background map and with the same TypeError: 
<img width="1440" alt="screenshot 2017-03-02 13 57 44" src="https://cloud.githubusercontent.com/assets/6911487/23522286/63fa6cde-ff50-11e6-8604-c5955834b1e2.png">

**Comment by Naigege** [comment]
@kamicut Here is another error in Macbook Safari. Thanks!
<img width="1440" alt="screenshot 2017-03-08 10 17 33" src="https://cloud.githubusercontent.com/assets/6911487/23709798/993c0640-03e8-11e7-890b-7317d565dfcd.png">

**Comment by Naigege** [comment]
@kamicut Is there any luck on the IE browser issue ? 

I used browserstack to check the compatibility on different OS and browsers. On browserstack, the preview works well on Windows 7 & firefox 49. However, it is not working on my desktop (one world bank machine) with same conditions. I am not sure why there is a difference. Below are the screenshots on the desktop:

![image](https://cloud.githubusercontent.com/assets/6911487/23773614/06b08812-04ee-11e7-8bf7-8d475e5dc098.png)
![image](https://cloud.githubusercontent.com/assets/6911487/23773628/17a660f6-04ee-11e7-96f3-03bda2fc059c.png)

**Comment by Naigege** [comment]
@olafveerman @kamicut 

I use browserstack to test different browsers on Windows OS. Below is the results: 
<img width="690" alt="screenshot 2017-03-13 00 04 09" src="https://cloud.githubusercontent.com/assets/6911487/23841030/9e2f9072-0780-11e7-800e-b7c1a129553d.png">

In summary, 
1. IE cannot run on windows OS whichever
2. even though browserstack shows Firefox 49 works well on Win7. But there are still some exceptions, like on my World Bank desktop. 
3. Windows XP is too old to support any browser

My free browserstack live time ends. I will do more test on Mac OS, iOS and Android next week. But for now, we should fix IE as most world bank laptop & desktop equip IE. 

Thanks a lot!

**Comment by kamicut** [comment]
Thanks @Naigege that helps us look into the issues and figure out if we can create a fallback visualization.

**Comment by olafveerman** [comment]
We were able to track this down to:

1. Fetch needs Promise, which needs to be polyfilled on IE and Safari
2. Lack of mapbox-gl support. We will display a more useful error message if the map can't be previewed
