### ISSUE TITLE
Initial install problems with newer docker version

### ISSUE THREAD

**Issue by volands** [energy-data/energydata.info#120]
Hi,

I try to install according the manual deployment instructions (https://github.com/energy-data/energydata.info#deploy-instructions). Unfortunately there seems to be problems with newer docker versions, I run:
- Ubuntu LTS 16.04.02
- Docker version 17.03.0-ce, build 60ccb22, API v1.26

There are some "deprecated" binding messages and especially the following error (traceback attached):

> APIError: 400 Client Error: starting container with non-empty request body was deprecated since v1.10 and removed in v1.12

```
(venv) user@energydata:~/energydata.info$ datacats init

/home/user/datacats/venv/local/lib/python2.7/site-packages/docker_py-1.10.6-py2.7.egg/docker/utils/utils.py:618: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
'docker.utils.create_host_config() is deprecated. Please use '
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats reload

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/home/user/datacats/datacats/datacats/cli/main.py", line 99, in main
    return command_fn(environment, opts)
  File "/home/user/datacats/datacats/datacats/cli/manage.py", line 125, in reload_
    environment.start_supporting_containers()
  File "/home/user/datacats/datacats/datacats/environment.py", line 276, in start_supporting_containers
    log_syslog=log_syslog
  File "/home/user/datacats/datacats/datacats/task.py", line 510, in start_supporting_containers
    log_syslog=log_syslog)
  File "/home/user/datacats/datacats/datacats/docker.py", line 296, in run_container
    port_bindings=port_bindings)
  File "/home/user/datacats/venv/local/lib/python2.7/site-packages/docker_py-1.10.6-py2.7.egg/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/user/datacats/venv/local/lib/python2.7/site-packages/docker_py-1.10.6-py2.7.egg/docker/api/container.py", line 383, in start
    self._raise_for_status(res)
  File "/home/user/datacats/venv/local/lib/python2.7/site-packages/docker_py-1.10.6-py2.7.egg/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 400 Client Error: Bad Request ("{"message":"starting container with non-empty request body was deprecated since v1.10 and removed in v1.12"}"
```

Hope you can help in this case or have an idea for solving.

Thanks and best regards,
Patrick

**Comment by volands** [comment]
https://github.com/datacats/datacats/issues/390

**Comment by stevenvandervalk** [comment]
@volands Did you end up solving this or rolling back your docker API version? If so, may I ask how? I'm not sure which `docker-engine` version still supports API `v1.12`?

**Comment by volands** [comment]
In my case I need to clone ```ckanext-authkey``` manually - there seems to be a broken reference (so ```git submodule --init --recursive``` don't include ```ckanext-authkey```).

Furthermore I was successfull with downgrading Docker. With API version >= 1.12 it don't work. For me a downgrade to <= 1.11 results in working ckan/energydata.info project - but there are still some configs to do and there are some deprecated function messages on startup.

**Comment by stevenvandervalk** [comment]
@volands Ya, I ran into the same issue https://github.com/energy-data/energydata.info/issues/152 with fix.

Sweet, thanks for the news!  Which package version of `docker-engine` on Ubuntu did you install to match <= 1.11?  https://docs.docker.com/engine/api/version-history/ wasn't much help so I was just guessing and dealing with https://github.com/moby/moby/issues/23347

**Comment by stevenvandervalk** [comment]
In case it helps anyone else, `docker-engine` `1.11.0` seems to be a sufficient downgrade on Ubuntu 16.04 against the datacats fork used.  Thanks very much to everyone on this project for the help and with datacats!
