### ISSUE TITLE
New user registration auto-reply email 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#132]
It seems no such an email for now.

**Comment by olafveerman** [comment]
@Naigege 
How are you inviting new users to the platform? If you do it the following way, it should send a welcome message:

1. Go to the organization you want to add a user to
2. 'Manage' > 'Members'
3. Click 'Add member'
4. On that page you can add an existing member, or add a new one by adding its email.

The new user currently gets the following message:

```
Dear [temporary user name],

You have been invited to Energy Data. A user has already been created to you with the username [temporary user name]. You can change it later.

To accept this invite, please reset your password at:

   [confirmation link]


--
Energy Data (https://energydata.info)
```

**Comment by Naigege** [comment]
@olafveerman If the user is not invited to register on <energydata.info>, the user will not receive any confirmation email. I already tested by creating an account, and I did not see any email sent to me. 
Should we use the SMTP server email to do it?
Thanks!

**Comment by olafveerman** [comment]
@Naigege 
Did you test this using the steps I described above?

**Comment by Naigege** [comment]
@olafveerman Yes. I just tested, it works for invited users. But here I am refering to the other users who are not invited by us, and just want to register an account on our platform. They click on "Register" button on front page, and not receiving any confirmation email after registration.

**Comment by Naigege** [comment]
@olafveerman I am not sure if I explain well on this. Could you set the auto-reply email as below? Please let me know you still have confusion. Thanks! 

Email Topic: Welcome to ENERGYDATA.INFO!
 
Email content: 

Welcome and thank you for joining!
 
ENERGYDATA.INFO is a collaborative open data and analytics platform providing a central location for organizations and individuals to share data and data analytics towards supporting sustainable energy developments, globally.
 
Our number one tip to get the most out of ENERGYDATA.INFO is to check our user manual at <https://energydata.info/dataset/energydata-info-user-manual>. It’ll help you get onboard swiftly.
 
Have a question? Need support? Just shoot us an email via <energydata@worldbankgroup.org>! We’re always here to help.
 
The ENERGYDATA.INFO Team
