### ISSUE TITLE
Add country and year to dataset list view

### ISSUE THREAD

**Issue by carderne** [energy-data/energydata.info#133]
Inspired from: https://data.humdata.org/dataset?sort=metadata_modified+desc

Ugly example:
![example1](https://cloud.githubusercontent.com/assets/19817302/24025319/0d28d30a-0a90-11e7-9b7c-f538d903c1b8.png)

Problems (and suggestions):
- Multiple countries (and regions)
 -> if <=5 countries, print them
 -> else if >5 countries and region exists, print that
 -> else if no region, print 5 countries and 'etc...' or something to that effect
- No 'Published year' on data set
 -> could change label and use upload date in this case?

**Comment by olafveerman** [comment]
Deployed
