### ISSUE TITLE
Error on change resource name

### ISSUE THREAD

**Issue by carderne** [energy-data/energydata.info#135]
Trying to change the name of the second resource in this dataset:
https://energydata.info/dataset/mozambique-electricity-transmission-network-2017

I get the following error message:
[server_error.pdf](https://github.com/energy-data/energydata.info/files/853479/server_error.pdf)

**Comment by carderne** [comment]
This happened again while trying to update a resource on this dataset:
https://energydata.info/dataset/small-and-mini-hydropower-potential-in-sub-saharan-africa

**Comment by carderne** [comment]
And trying to add a resource to the same dataset.

**Comment by Naigege** [comment]
@olafveerman This looks the same issue as #102

**Comment by olafveerman** [comment]
@carderne @Naigege 
This is related to the recent changes we made to the metadata scheme. The `topic` field is mandatory, but the datasets you reference don't have a `topic` specified. When updating an associated resource, CKAN does checks and throws the - not very useful - error.
Editing the dataset and adding a `topic` should solve it. I added one to the Mozambique network to test. Please check if I added the correct one.

cc @yanntanvez

**Comment by olafveerman** [comment]
Closing this.

**Comment by Naigege** [comment]
@olafveerman Thanks a lot! The topic is right.
