### ISSUE TITLE
Previously previewed GeoJSON cannot be previewed now

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#139]
@olafveerman there are some geojson which can be previewed before, cannot be previewed currently. Is it caused by file size too big? Below are some samples:

https://energydata.info/dataset/myanmar-populated-settlements-data/resource/24be943e-ebd3-41d2-a588-8c3cb1d01a0b

https://energydata.info/dataset/uganda-rivers/resource/ca4e10e2-6ffc-41d2-940b-54dd43f1c0c1

https://energydata.info/dataset/road-network/resource/5743938d-e59a-4368-9c25-ba687589c7c9

<img width="946" alt="screenshot 2017-03-23 00 22 47" src="https://cloud.githubusercontent.com/assets/6911487/24232077/db335f0e-0f5e-11e7-8db0-3f0b403ed194.png">

**Comment by jodiegardiner** [comment]
I have investigated this and it is caused by the file size.  Previewing a 40mb geojson file would seriously affect server performance.
