### ISSUE TITLE
Not urgent & check after launch - revise the google search result

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#144]
![image](https://cloud.githubusercontent.com/assets/6911487/24490203/917338e4-14ef-11e7-85a2-15064ac78d5c.png)

**Comment by Naigege** [comment]
Write "about" section to reflect on google search paragraph.

**Comment by carderne** [comment]
See PR #150 

Also change the 'title' for the Google result to: `Welcome – ENERGYDATA.INFO`

**Comment by Naigege** [comment]
@olafveerman please note this issue is referring to Google text revision. Thanks!

**Comment by olafveerman** [comment]
This was fixed:

![image](https://user-images.githubusercontent.com/751330/26992990-2e6da720-4d2f-11e7-8b6d-a45c0342a1a0.png)
