### ISSUE TITLE
CSV file is displayed in a single column

### ISSUE THREAD

**Issue by ClaraIV** [energy-data/energydata.info#148]
We have a problem with Excel/CSV files that do not respect the standard format. It seems like there is some data parsing that detects headers and since the first header is composed out of a single column it merges the following columns (next rows) into one column.
Please see here the excel file: https://energydata.info/dataset/pakistan-solar-measurement-wbg-esmap/resource/38350b3c-677e-4fe5-9109-11915df7c18b
Please see here the excel file translated into csv: https://energydata.info/dataset/pakistan-solar-measurement-wbg-esmap/resource/5cf06dcb-9786-4234-8496-d32cd75005de 
And please see here a work-around that is not ideal:  https://energydata.info/dataset/pakistan-solar-measurement-wbg-esmap/resource/44505227-c184-457a-8b36-4e62068e0146

Can you deactivate the parsing of the header or modify the preview so that it looks like a usual text editor?

**Comment by Naigege** [comment]
@olafveerman I remember we discussed the excel & csv preview is based on the header row. For example, only the first column will be shown on CKAN for excel workbook below: 
<img width="853" alt="screenshot 2017-04-10 10 34 07" src="https://cloud.githubusercontent.com/assets/6911487/24866937/adb39358-1dd9-11e7-9965-faac1a03ea84.png">

Could you help us to check if there is a way to preview the excel & csv files in a good format? @ClaraIV is working on data provider side. She can re-organize the header row to make it not perfect but visualized on platform. Please let us know the best solution. Thanks!
