### ISSUE TITLE
New App Integration - GTF 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#149]
App name: GTF
Attribution: World Bank Group http://www.worldbank.org//
Description: Global Tracking Framework (GTF) provides a global dashboard to register progress on energy access, energy efficiency and renewable energy.

The existing app link is http://gtf.esmap.org/

Please let me know if you need more info. Thanks!

**Comment by Naigege** [comment]
Please also arrange the app layout and make "RISE" and "GTF" replace the "Electrification Path" and "Climatescope" positions (4th and 5th app), and let "Climatescope" be the last app on the page. 

Thanks!

**Comment by olafveerman** [comment]
Deployed
