### ISSUE TITLE
git submodule update --init --recursive fails on ckanext-authkey ref

### ISSUE THREAD

**Issue by stevenvandervalk** [energy-data/energydata.info#152]
Hi. Awesome project! Super excited to see a working version of datacats!  Following the initial provisioning instructions immediately ran into 

```
Submodule path 'ckan': checked out '84938a42d5c45fbfb3027286111458622d3478c3'
error: no such remote ref 816c8d4f9e440803e530d35a485b1ea27970ca9c
Fetched in submodule path 'ckanext-authkey', but it did not contain 816c8d4f9e440803e530d35a485b1ea2
7970ca9c. Direct fetching of that commit failed.
```

After `git submodule update --init --recursive` on both `develop` and `master` branches.
Apologies if I missed something obvious.

**Comment by stevenvandervalk** [comment]
So it seems https://github.com/energy-data/energydata.info/commit/0f76c30ade0f955ec94ec9a6f300a95a3f28f4b5 adds in the breaking change since it refers to @davidread fork.  It seems reverted by altering `.gitmodules` entry for `ckanext-authkey` url value to `url = https://github.com/davidread/ckanext-authkey` and then running the original `git submodule --init --recursive` (in case you didn't do the initial clone with --recursive).

I'm confused why nobody else runs into this besides me but it seems to work for me now so just documenting in case useful for anyone else.   Thanks for sharing the project!

**Comment by kamicut** [comment]
Thanks for opening this issue @stevenvandervalk, the commit `816c8` was referring to a non-merged pull request. I think it should work now.

**Comment by stevenvandervalk** [comment]
@kamicut thanks, works now from clone.  Also, I tried out the deploy instructions but ran into this issue https://github.com/energy-data/energydata.info/issues/120.  Did you good people pin a certain `docker-engine` version when you deployed to get it to work?
