### ISSUE TITLE
New app - Electrification Pathways

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#155]
Please integrate & add the electrification model app into <energydata.info> by **July 19**. 

The code is saved in <https://github.com/energy-data/nzt-electrification>. And the URL is <http://electrification.energydata.info>. 

App name: Electrification Pathways
Attribution: THE WORLD BANK (http://www.worldbank.org/), KTH UNIVERSITY (https://www.kth.se/en) and ESMAP (https://www.esmap.org/).
Description: Navigate least cost electrification options for each 1 by 1 km square in Nigeria, Tanzania and Zambia. Works on Chrome, Firefox and Safari.

Naichen will create a pull request to link this app.

**Comment by Naigege** [comment]
please do not bring the electrification tool up until further notice. Sorry for the confusion.

**Comment by Naigege** [comment]
@olafveerman please check 2 new pull request. 

Please also put the Africa Electricity Grids Explorer & this app on the front page as featured app. Thanks a lot!

**Comment by Naigege** [comment]
@olafveerman could you also change the app number from 9 to 10 on the home page please? If I can do it, please direct me to the coding repository and I will submit a PR. 

Thanks a lot!

**Comment by olafveerman** [comment]
@Naigege 
You can change the app number here: https://github.com/energy-data/energydata.info/blob/develop/ckanext-offgridtheme/ckanext/offgridtheme/templates/home/index.html#L54

**Comment by Naigege** [comment]
@olafveerman I just submit a PR, please see if it is good. Thanks a lot!

**Comment by olafveerman** [comment]
Already merged and live. THanks

**Comment by Naigege** [comment]
@olaf, I need to change the screenshot, and make a small revision on the attribution line. Please see the PR:)

**Comment by olafveerman** [comment]
All PR's merged

**Comment by Naigege** [comment]
@olafveerman thanks a lot for your instant help, and sorry for the back and forth! 

1. I made a small change on the attribution line, and send another PR. 
2. I see on the front page, the attribution line is still in the old style as below: there is an "AND" between WORLD BANK GROUP & KTH UNIVERSITY

<img width="470" alt="screenshot 2017-07-19 12 07 26" src="https://user-images.githubusercontent.com/6911487/28377490-eef47644-6c7a-11e7-8e18-be9b97d9337b.png">

But I am trying to change it the new style which is currently shown on app page: "BY THE WORLD BANK GROUP，KTH UNIVERSITY AND ESMAP".

Thanks a lot!

**Comment by olafveerman** [comment]
Just made the change on the homepage.
For future reference, the homepage is updated here: https://github.com/energy-data/energydata.info/blob/develop/ckanext-offgridtheme/ckanext/offgridtheme/templates/home/index.html

**Comment by Naigege** [comment]
@olafveerman thanks a lot!
