### ISSUE TITLE
New App: Myanmar Off-Grid Analytics

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#159]
App name: Myanmar Off-Grid Analytics
Attribution: INTEGRATION (www.integration.org) & Reiner Lemoine Institut (www.reiner-lemoine-institut.de)
Description: Visualizes data of the current status of electrification and presents renewable energy potentials to showcase the off-grid investment potential

The existing app link is http://adb-myanmar.integration.org/ 
Please let me know if you need more info. Thanks!

**Comment by olafveerman** [comment]
Deployed.
