### ISSUE TITLE
Preview Excel file

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/energydata.info#16]
![image](https://cloud.githubusercontent.com/assets/21108014/19394793/950ffdda-9208-11e6-8b87-07777ba16ab6.png)

**Comment by yanntanvez** [comment]
![image](https://cloud.githubusercontent.com/assets/21108014/19394820/b2e012c8-9208-11e6-9e50-a969166d39b2.png)

**Comment by olafveerman** [comment]
@yanntanvez 
The uploaded file is an Excel file. I uploaded the same dataset in CSV format and the preview is working properly: https://ifc.ds.io/dataset/mingov-botswana

**Comment by olafveerman** [comment]
I was about to close this issue as well. :+1: 

It seems that other Excel files work well: https://energydata.info/dataset/pakistan-solar-radiation-measurements-hyderabad/resource/b650e341-b502-4edd-bb0c-4c9cf65a9db7
