### ISSUE TITLE
Transmission datasets unavailable when clicking 'go to resource'

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/energydata.info#17]
Hi Team,

Could you let me know what is the issue here? Is this a misuse of the platform by Dimitris or a bug? 

Ideally, these situations should not happen and if this is a misuse, we should understand how a person that is very proficient in GIS/data cannot use the platform as intended and see if we can prevent this from happening.

Thanks,
-Yann

![image](https://cloud.githubusercontent.com/assets/21108014/19395461/b365a390-920b-11e6-96b7-6b8d40bd0fe7.png)

![image](https://cloud.githubusercontent.com/assets/21108014/19395467/bb0ec630-920b-11e6-8dda-bebb03b595c7.png)

**Comment by olafveerman** [comment]
The uploaded file is an Excel file. I uploaded the same dataset in CSV format and the preview is working properly: https://ifc.ds.io/dataset/mingov-botswana

**Comment by olafveerman** [comment]
It seems that Dimitris add a URL to a link on box.com
We'll check what's going on and why the Resource link is not properly formatted.

cc @kamicut
