### ISSUE TITLE
Upload csv & zip file error

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#177]
The user try to upload the attached csv file through website to update existing dataset - [Maldives - Solar Radiation Measurement Data (2015 - 2017)](https://energydata.info/dataset/maldives-solar-radiation-measurement-data). The same error happens when the user uploads zip file as well. 

We firstly observed too many semicolons in the csv file, but user reports a same structure csv file was uploaded successfully on another [Zambia dataset](https://energydata.info/dataset/zambia-solar-radiation-measurement-data-2015-2017/resource/6975d8e9-8655-4a2e-8142-34fd57b1256f).

I try to upload it by myself and see the error message as below. 
<img width="975" alt="screenshot 2017-06-15 11 12 27" src="https://user-images.githubusercontent.com/6911487/27188448-32b725d6-51bc-11e7-8142-94654383a900.png">

[Solar-Measurements_Maldives_Gan_WB-ESMAP_Header.csv.zip](https://github.com/energy-data/energydata.info/files/1078073/Solar-Measurements_Maldives_Gan_WB-ESMAP_Header.csv.zip)

**Comment by olafveerman** [comment]
We ran a couple of tests and it is possible to upload this file to a new package.
It seems that the Maldives dataset doesn't have the published date, which was made mandatory a couple of weeks ago. Could you add the published year to the dataset metadata and try the upload again?

**Comment by Naigege** [comment]
Thanks Olaf! Will ask the user to upload again. If everything goes well, I will close this issue.

Also, could you add an mandatory symbol for published year? 
<img width="557" alt="screenshot 2017-06-15 13 16 43" src="https://user-images.githubusercontent.com/6911487/27193463-e63240ae-51cc-11e7-9e7d-42a2db3cad78.png">

**Comment by olafveerman** [comment]
@Naigege Yes, we added the asterisk.

**Comment by Naigege** [comment]
@olafveerman Could you also add the asterisk on the left side, the same style as Title, Description  please? 
![image](https://user-images.githubusercontent.com/6911487/27247296-2ad185a0-52c5-11e7-9c3f-a4db6f397893.png)

**Comment by Naigege** [comment]
link to issue #227
