### ISSUE TITLE
Reorder resources-not working

### ISSUE THREAD

**Issue by ClaraIV** [energy-data/energydata.info#181]
The option to reorder resources in a dataset doesn't seem to be working.

**Comment by olafveerman** [comment]
@ClaraIV Could you provide more information about what you're experiencing, and what system you're using?
Reordering resources should be working as follows:

![resources-reorder](https://user-images.githubusercontent.com/751330/27388046-587b823e-5668-11e7-8c38-eaca5b46fb07.gif)

**Comment by ClaraIV** [comment]
Hi Olaf,

Thanks for the video, that's very helpful! My intuition led me to click on the symbol on the left and nothing happens when I do that. But drag&drop on the tab works well.
