### ISSUE TITLE
Metadata not showing currently 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#182]
The metadata is not showing on the dataset page (checked on IE, chrome, safari firefox on laptop & Safari and chrome on iphone). Could you check it ASAP? Is it related to the data webpage re-organized? Because it was good before. Thanks a lot! 

![image](https://user-images.githubusercontent.com/6911487/27539678-65e581cc-5a4b-11e7-8041-39dd433dcb88.png)

**Comment by olafveerman** [comment]
@Naigege This is fixed now. If it doesn't show immediately, please do a hard refresh.
