### ISSUE TITLE
Region names too long & revise "Region" metadata field

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#185]
should use “+x” feature for Region to keep 1 single line for “Countries” “Regions” & “Published Year”. Should we aim to show 2 region name, and use “+x”?  To be safe, perhaps only 1 region name can be shown, or reduce the shown country number. 

<img width="689" alt="screenshot 2017-06-27 17 12 37" src="https://user-images.githubusercontent.com/6911487/27610591-f7ac2518-5b5c-11e7-86d5-76f9e3a2cca8.png">

**Comment by Naigege** [comment]
@olafveerman Is there a better way to fix this?

**Comment by Naigege** [comment]
I suggest that in the "Region" metadata field, we should have:
 
1. "Global" as a new option
2. change "Africa" to "Sub-Saharan Africa"

Thanks!

**Comment by jodiegardiner** [comment]
@shandaoz Is this still a relevant issue?

**Comment by jodiegardiner** [comment]
> Yes, but in a slightly different way. I noticed that for some datasets there is a "+" displayed under the dataset title, when the number of countries exceeds 4. However, other datasets with more than 4 countries are all listed. Can we keep this display consistent to list a max of 3 countries with "+" behind for datasets with more than 3 countries?  


![number](https://user-images.githubusercontent.com/36420556/48571816-d12f0d80-e8d5-11e8-8a4d-883925823442.PNG)

**Comment by jodiegardiner** [comment]
Regions and Countries currently behave differently it seems. Will limit to max 4.

**Comment by jodiegardiner** [comment]
Fixed on staging. Pull to prod out of hours.

**Comment by shandaoz** [comment]
Great!

**Comment by jodiegardiner** [comment]
successfully pulled last night.

**Comment by shandaoz** [comment]
Looks good! Thanks Jodie!
