### ISSUE TITLE
Animation for counting number of dataset, app, organization & countries

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#186]
The animation is counting the datasets, app, organization & countries from 0 to current numbers.) The counts should appear with some animation like on HDX website. Please check <https://data.humdata.org/>. 

As discussed before, it will take up to 2 hours to create this on the front page.

**Comment by jodiegardiner** [comment]
I have implemented this and it is viewable now on the front page of staging. Deployed to live in next push.
