### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by ClaraIV** [energy-data/energydata.info#19]
I get this error when trying to upload a new resource;

**Comment by olafveerman** [comment]
@ClaraIV Do you see this behavior consistently, or is it with a particular file?

**Comment by ClaraIV** [comment]
Not consistenly; take a look at this dataset: https://ifc.ds.io/dataset/malawi-solar-kasungu-measurementdata-esmap
I'm trying to add the last resource (dataset for July) and I can't. I couldn't do it on Friday and I can't do it now.
Right now I'm trying to upload a .tif file to see how that looks on the platform and I get the same error.

**Comment by olafveerman** [comment]
What's the file size?

**Comment by olafveerman** [comment]
This was due to the disk size that we're using in staging. We'll be increasing the size in the afternoon.
