### ISSUE TITLE
Please help - set up tracking code for Electrification Pathways

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#198]
@olafveerman I am trying to have the new app - Electrification Pathways set up in the Google analytics to track the traffic on it. 

I need to set up the tracking code by inserting the code below to each webpage to be tracked. To do this, paste the entire snippet below into the HTML on the web pages, just before the closing </head>tag. I assume it requires some pull requests within <https://github.com/energy-data/nzt-electrification>, but I cannot identify the right files to make changes. Could you help on it please?

"<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-81901426-5', 'auto');
  ga('send', 'pageview');

</script>"

The code required is within quotation marks.

**Comment by olafveerman** [comment]
Closing. Will be done in other repo.
