### ISSUE TITLE
No Download option for PNG files

### ISSUE THREAD

**Issue by ClaraIV** [energy-data/energydata.info#20]
Dear team,

I uploaded a .png file here: 
https://ifc.ds.io/dataset/test-pngfile/resource/4977f38d-fd3d-4388-b548-db0f17244aff

and I don't see any download option for this. How can I retrieve if from the platform?

Many thanks,
Clara

**Comment by olafveerman** [comment]
@ClaraIV 
For now, you can click on `Go to Resource` to see and download the PNG
