### ISSUE TITLE
Connection Security Error

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#203]
The site cannot be opened due to a connection security error. Need to find out the error root to avoid happening again. 
![connection_security_issue](https://user-images.githubusercontent.com/6911487/31371407-9153dd2a-ad5e-11e7-980e-679def90a21b.jpg)

**Comment by olafveerman** [comment]
This was due to an expired certificate.
We renewed the cert yesterday and this issue should be resolved now.
