### ISSUE TITLE
Revert logo to previous design

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#206]
Re-include “An innovation of the World Bank Group” under the ENERGYDATA.INFO logo - make it the same logo that was there before.

**Comment by jodiegardiner** [comment]
@shandaoz Is this still a valid ticket?

**Comment by shandaoz** [comment]
@jodiegardiner Yes, it is still a valid ticket.

**Comment by jodiegardiner** [comment]
This has been changed on staging. Please view and close if satisfied.  I am unsure how it looked before as that was before Derilinx's involvement. 

@shandaoz

**Comment by shandaoz** [comment]
The new logo looks good!
