### ISSUE TITLE
Strange Page Button on dataset website

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#212]
![image](https://user-images.githubusercontent.com/6911487/37802639-b2fb4fa2-2e01-11e8-8ad0-080f65d80943.png)

**Comment by jodiegardiner** [comment]
Hi Naichen.  Can you tell me where you are seeing this (i.e. what search terms or filters are applied?). Can you also tell me which browser you are using?

I am not able to replicate this one in the popular browsers.

**Comment by jodiegardiner** [comment]
Closing this as it is not reproducible.  Please reopen if this issue is encountered again.
