### ISSUE TITLE
Strange metadata field when uploading dataset - Maintainer 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#213]
The Maintainer field which is not seen on the page prevents uploading a new dataset/updating an existing dataset. 
![maintainer](https://user-images.githubusercontent.com/6911487/37930073-a7383c96-310f-11e8-802f-d6c3538a19aa.JPG)

The examples links are:
https://energydata.info/dataset/zimbabwe-population-density-2015 
https://energydata.info/dataset/vietnam--population-density-2015

**Comment by jodiegardiner** [comment]
Fixed.  Rebuilding now.
