### ISSUE TITLE
Unexpected mandatory field when uploading a new dataset - URL field

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#214]
Before, the URL was default by the system.
![url mandatory field](https://user-images.githubusercontent.com/6911487/37930709-8b568c74-3111-11e8-9bb5-9ed106ad1abf.jpg)

**Comment by jodiegardiner** [comment]
Fixed on staging.  Will be pushed live during next window of offpeak opportunity

**Comment by jodiegardiner** [comment]
Pushed to production.
