### ISSUE TITLE
File too large to be uploaded issue 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#215]
The file size case by case, but even for a geojson file with 12 MB only, but cannot be uploaded.

**Comment by jodiegardiner** [comment]
File size limits boosted to 100mb across the board.

**Comment by Naigege** [comment]
Hi Jodie, if the file is bigger than 100mb regardless of the format, the file cannot be uploaded?

**Comment by shandaoz** [comment]
Hi Jodie! I was uploading a 35 MB Geojsonfile for a dataset (https://energydata.info/dataset/subcounty-boundaries-2014), but the platform still indicated that the file was too large for upload. 
![too large](https://user-images.githubusercontent.com/36420556/38101471-6071fbb2-334e-11e8-904b-5a709bebae08.JPG)
![file too large](https://user-images.githubusercontent.com/36420556/38101525-821df374-334e-11e8-9b4d-f67339e4e609.JPG)

**Comment by jodiegardiner** [comment]
Hi all.  I have now set the maximum file size to 2gb.  I have tested just now with a 40mb geojson and it was uploaded without issue.  I am not sure why the 35mb file was failing but if you could try it again now and let me know that would be great.

**Comment by shandaoz** [comment]
Hi Jodie. Thanks for your update! I can now upload all the files that I wasn't able to upload earlier.

**Comment by jodiegardiner** [comment]
Great.  I shall close this again in that case.
