### ISSUE TITLE
[Urgent] Data API via resource's ID does not work 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#216]
There are 3 examples: 
a.	Hydro-connected Solar PV potential (test)
                   https://energydata.info/api/action/datastore_search?resource_id=10466022-d770-4d41-9caf-6094be6c9a35
b.	Solar Measurement Sites (test)
https://energydata.info/api/action/datastore_search?resource_id=fc377e32-dd81-4f7e-8d8b-fd6a30aa29f3
c.	Solar Measurement Sites (production)
              https://energydata.info/api/action/datastore_search?resource_id=3d76335d-d744-4e70-8384-f83d0a096422

**Comment by jodiegardiner** [comment]
The resources have all been recovered and pushed to the datastore where the file size limits allowed.

a) and c) above both function as intended and b) is a deleted dataset.  In this case, a test dataset that was created and deleted on the same day to be replaced by the production version (which is c) above).  External apps should update their urls accordingly.

**Comment by moravcik** [comment]
The a) and b) resources work, but it seems there were some changes with CORS configuration, so I am not able to call the API from globalsolaratlas.info website.

I am getting the `No 'Access-Control-Allow-Origin' header` error:

    XMLHttpRequest cannot load https://energydata.info/api/action/datastore_search?resource_id=3d76335d-d744-4e70-8384-f83d0a096422&limit=1000. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://globalsolaratlas.info' is therefore not allowed access.

Is there any JSONP option available, or can you add globalsolaratlas.info (and worldbank-atlas-test.herokuapp.com) domain to allowed domains?

**Comment by jodiegardiner** [comment]
Hi moravcik.  CORS access control has been configured now so you should be able to call the API externally.  I have checked and the http://africagrid.energydata.info/ app can access the data now.

**Comment by moravcik** [comment]
Thank you @jodiegardiner, it works also for globalsolaratlas.info

**Comment by jodiegardiner** [comment]
Great!

**Comment by ClaraIV** [comment]
Hi @jodiegardiner 

I'm not sure I understand what the problem was with the API requests? What was the update that needed to happen for this to work again?

We have the same problem with the Global Wind Atlas (https://globalwindatlas.info/) which is not displaying the location info contained in this dataset:  https://energydata.info/dataset/global-wind-masts-inventory/resource/c412ca57-bbc8-4a57-9793-3e9a9d330fe6

**Comment by jodiegardiner** [comment]
Hi @ClaraIV 

The fix for this was enabling access-control allow origin.  In order to do a datastore api call though, the resource must be in the datastore in the first place, obviously.  This was not the case for the resource you linked above.  It is in there now.  The wind atlas looks good to me now.

**Comment by ClaraIV** [comment]
Hi @jodiegardiner 

Thanks for the fast reply. What do you mean it was not in the datastore in the first place? Who moved it out? It worked before the maintenance so we're trying to understand what happened that caused the API requests to stop working and why do you need to manually "move" the resources back in the datastores.
Thanks for your help.

**Comment by jodiegardiner** [comment]
Hi @ClaraIV 
When we took over maintenance, we essentially recreated the site using a modern CKAN version then replicated the existing setup as closely as possible on a totally different host server.  Part of that was copying the resources into the filestore and also sending those resources to the datastore. In some isolated cases this last part had some issues.  Those issues should be resolved now, but the result is that a couple of resources were missing from the datastore.

**Comment by ClaraIV** [comment]
Hi @jodiegardiner 

Thanks for the information, useful to know.
