### ISSUE TITLE
Strange User Interface When uploading/updating a dataset

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#217]
Missing remove button for the URL, and no button to upload new dataset...

![screenshot_upload](https://user-images.githubusercontent.com/6911487/38048529-a36500ba-3293-11e8-95a4-c57f6caa6b10.png)

**Comment by Naigege** [comment]
I want to simply replace one existing dataset, and keep all the metadata info the same - <https://energydata.info/dataset/road-network-afghanistan/resource/281f23ce-16e7-42e7-ad08-54669a150bfc>. But it does not work, the "Upload" or "Link" buttons do not work: 

![image](https://user-images.githubusercontent.com/6911487/38271629-f4525872-3754-11e8-89ee-bdeeee57cc9f.png)

For now (to cross this issue), I will create a new dataset and delete the previous one which I cannot replace.

**Comment by shandaoz** [comment]
When uploading a dataset, the platform does not self-generate a URL for the uploaded dataset. 

![8](https://user-images.githubusercontent.com/36420556/38584288-da7f811a-3ce3-11e8-97b1-eefa8f029d77.JPG)

**Comment by Naigege** [comment]
#228 is the relevant issue.

**Comment by jodiegardiner** [comment]
I will close this and fix #228
