### ISSUE TITLE
Two authors entries not valid

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#219]
![1](https://user-images.githubusercontent.com/36420556/38107868-18f82708-3361-11e8-8281-d4fd5f8712c7.JPG)
![2](https://user-images.githubusercontent.com/36420556/38107904-30cb95fe-3361-11e8-94fb-1340f9db15e4.JPG)
Before the migration the platform allowed us to input more than one anothor email addresses in one entry, but now we cannot.

**Comment by jodiegardiner** [comment]
Fixed and pushed to production. Tested and working.

**Comment by shandaoz** [comment]
![two authors](https://user-images.githubusercontent.com/36420556/39318894-dd538d2c-496e-11e8-8d5a-c78e47d39ab5.PNG)

Hi Jodie! Thanks for fixing the issues. 
I noticed that while metadata update now allows the user to input two authors, only the first author can be contacted. Since on the metadata interface, only the first author’s email can be opened. Could you fix this issue and allow both authors emails be displayed? 
https://energydata.info/dataset/eastern-africa-power-pool-renewable-energy-zones-solar-pv

**Comment by jodiegardiner** [comment]
Hi Shandaoz.  This is now fixed!  It is important that both the author and author email fields are filled in, and also important that they are separated by commas.
