### ISSUE TITLE
URL not recognized

### ISSUE THREAD

**Issue by ClaraIV** [energy-data/energydata.info#22]
I'm trying to add this URL : http://irena.masdar.ac.ae/?map=1708 
as a resource; it seems it's not being recognized.
When I click ""Go To Resource" it takes me to the homepage: https://energydata.info/

The dataset is here: https://energydata.info/dataset/test-datasetirena

Many thanks for your help!

**Comment by olafveerman** [comment]
Thanks for reporting @ClaraIV . This is the same behavior as reported in #17.
I'll close this issue and we can track the fix against the other.
