### ISSUE TITLE
Total number of datasets do not match 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#220]
![3](https://user-images.githubusercontent.com/36420556/38108753-d2fa17ea-3363-11e8-94d1-17c170d934c6.JPG)
![4](https://user-images.githubusercontent.com/36420556/38108754-d30b20c6-3363-11e8-8b13-69962c00a71b.JPG)
The total number of datasets displayed on the front page is 402, but the number is displayed as 401 on the datasets page.

**Comment by jodiegardiner** [comment]
Fixed.
