### ISSUE TITLE
Search function does not work within organization page 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#221]
When go to an organisation page firstly, then use the search bar within the organization page, the results are always 0 
![image](https://user-images.githubusercontent.com/6911487/38114752-8de969c6-3377-11e8-828f-de0e22d9a3c8.png)

**Comment by jodiegardiner** [comment]
This is fixed on staging and will be deployed in the next window.

**Comment by jodiegardiner** [comment]
Deployed to production.
