### ISSUE TITLE
URL changes after content update 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#222]
Hi! I have encountered a strange problem when making updates and is wondering why it seems to be occurring randomly for different datasets.
When I make updates on a page, it generates a new URL, basically adding a "-" behind the original URL. After the updates, the original URL can no longer be opened. 
Thanks!
![1](https://user-images.githubusercontent.com/36420556/38257857-1d70405a-372f-11e8-8daa-1c78f38b3953.JPG)
![2](https://user-images.githubusercontent.com/36420556/38257861-1fcaa282-372f-11e8-8c5a-e8fb8371f53c.JPG)

**Comment by jodiegardiner** [comment]
The URL is generated automatically from what is entered into the title box.  If an extra character has appeared there it is because the title has been changed.

To prevent this behaviour from happening, do not change the title (unless you want the URL to change).
