### ISSUE TITLE
Pdf preview does not work 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#223]
The pdf preview does not work for the dataset <https://energydata.info/dataset/kazakhstan-transmission-substations-2016/resource/0aa70538-aa68-47bc-aeea-c8f1be9b0d51>
![image](https://user-images.githubusercontent.com/6911487/38267342-2dd2acfc-3749-11e8-9fc7-e8da29828e6e.png)

Also, there is a warning showing up after clicking on the "Manage" button
![image](https://user-images.githubusercontent.com/6911487/38267317-1b17a248-3749-11e8-8b6e-987a59036c91.png)

**Comment by jodiegardiner** [comment]
Fixed

https://energydata.info/dataset/kazakhstan-transmission-substations-2016/resource/0aa70538-aa68-47bc-aeea-c8f1be9b0d51
