### ISSUE TITLE
Integrate the Nigeria Rural Electrification Planning

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#224]
App name: Nigeria Rural Electrification Planning
Attribution: INTEGRATION (www.integration.org) & Reiner Lemoine Institut (www.reiner-lemoine-institut.de)
Description: Visualizes rural electrification plans of the five Federal Nigerian States of Cross River, Niger, Ogun, Plateau and Sokoto
App link: http://rrep-nigeria.integration.org/

@jodiegardiner Please integrate this app on the <https://energydata.info/apps>. We need specific size for the app's preview screenshot to be shown on the webpage.

**Comment by jodiegardiner** [comment]
Hi Naichen,

I've implemented the app here:

https://energydata.info/apps

Please check you are happy with everything and if so, close the ticket please.
