### ISSUE TITLE
Climatescope 2017 Preview Screenshot does not work

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#225]
![image](https://user-images.githubusercontent.com/6911487/38274575-2a7d5516-375d-11e8-855c-d43f92a8de03.png)

On the app page: https://energydata.info/apps

**Comment by jodiegardiner** [comment]
Can you give a bit more info please @Naigege ?

I'm not 100% sure what the specific issue is.

Thanks.

**Comment by Naigege** [comment]
![image](https://user-images.githubusercontent.com/6911487/38321164-c072ed18-3804-11e8-8176-2aca58a7c071.png)

It should be like this....

**Comment by jodiegardiner** [comment]
Ah I see.  Fixed now.
