### ISSUE TITLE
Slow Platform Response 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#226]
Hi ! The platform performance speed is not very stable. Sometimes the site response is very slow, other times it works just fine. Please improve the site response speed so that it's more consistent. Thanks !

**Comment by jodiegardiner** [comment]
I am unable to replicate this behaviour.  If there is a particular activity that is being performed slowly then I can look at this further but all the monitoring tools show site load and response rate within normal parameters. One might notice slow response immediately upon uploading a large resource.  This is to be expected.
