### ISSUE TITLE
Adding asterisk for mandatory fields 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#227]
![6](https://user-images.githubusercontent.com/36420556/38583706-d98f81ee-3ce1-11e8-8555-2f41efe59b2b.JPG)
Hi! We would like to add an asterisk in front of the "author" and "publishing date" fields as well. Thank you!

**Comment by jodiegardiner** [comment]
This has been fixed on staging. Will go live in next deploy.
