### ISSUE TITLE
Clear upload option for data uploads does not work 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#228]
Hi!
There is no “clear upload” option when the user is uploading a dataset for the first time. This option only appears for existing attached files. However, even when the “clear upload” button is selected, nothing happens before or after submission ( it does not remove the original file). This option vanishes when the uploaded data is  re-opened a second after submission.  Thank you! 
![7](https://user-images.githubusercontent.com/36420556/38584084-3924ef58-3ce3-11e8-8cfe-1d9bf83e6347.JPG)

**Comment by jodiegardiner** [comment]
This issue is now fixed.  I also reverted the change i made for #217 as the fix for this one offers a better solution.
