### ISSUE TITLE
Change Resource ORDER - not working

### ISSUE THREAD

**Issue by ClaraIV** [energy-data/energydata.info#23]

**Comment by olafveerman** [comment]
@ClaraIV 
I just tested it and this seems to work for me. Do you see this behavior on a particular dataset?

**Comment by ClaraIV** [comment]
I tried it here: https://energydata.info/dataset/resources/test-datasetirena

**Comment by olafveerman** [comment]
@ClaraIV Could you provide some more information, like browser used?

I was able to change the order for that dataset:

![image](https://cloud.githubusercontent.com/assets/751330/19889182/ee9234c2-a009-11e6-9d39-6a9f79eb3b26.png)

![image](https://cloud.githubusercontent.com/assets/751330/19889198/039ac24e-a00a-11e6-8de6-b5e9185ab001.png)

**Comment by ClaraIV** [comment]
I'm using Google Chrome;

**Comment by olafveerman** [comment]
Tested on different platforms and browsers. Seems to be working now. Please reopen if you encounter this again.
