### ISSUE TITLE
Urgent - privacy error

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#233]
![image](https://user-images.githubusercontent.com/6911487/41620434-b8ab48aa-73d7-11e8-8a78-fbe0791865e7.png)

@deirdrelee @jodiegardiner

**Comment by jodiegardiner** [comment]
Hi Naichen, I am dealing with this now

**Comment by jodiegardiner** [comment]
Hi Naichen, the site SSL cert had expired despite being set to autorenew.  It is fixed now.
