### ISSUE TITLE
DDH data harvester development

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#234]
@deirdrelee @TigranParvanyan @JemiTheKey 

As discussed on June 11, please send us the updates/reports regarding the DDH harvester development. 

![image](https://user-images.githubusercontent.com/6911487/41667389-dbcfe590-747a-11e8-9322-c3fab902dcb1.png)

**Comment by jodiegardiner** [comment]
This was delivered before I went away on vacation. It has not been deployed to Production yet.

**Comment by jodiegardiner** [comment]
New request to strip out titles from the DDH to EEX nightly harvest.

**Comment by jodiegardiner** [comment]
Salutations!

I have completed the following edits:
A validation report is now produced and email after harvesting is complete.
Use ddh['last_update'] as metadata_modified
Use ddh['release_date'] as metadata_created

**Comment by jodiegardiner** [comment]
Further, I have stripped the Year out of all the titles where one remained.

All this progress is visible on the staging server.

**Comment by jodiegardiner** [comment]
This is long since delivered. Please use new tickets for reporting bugs or issues or feature requests.
