### ISSUE TITLE
Error - Egypt - Electricity Transmission Network (2017)

### ISSUE THREAD

**Issue by Shahmed** [energy-data/energydata.info#235]
Hello, 

I am trying to download GIS data concerning (Egypt - Electricity Transmission Network (2017))
which can be found on
https://energydata.info/dataset/egypt-electricity-transmission-network-2017/resource/70cd56e7-5b9f-4d9e-8ca3-564283ae333a

However, I am not able to download it, I tried many times but I still get errors and the map-page is redirected to a code-page. I tried different browsers but I keep getting errors. 
Please find attached a file that contains screen prints of what I tried
[Error.docx](https://github.com/energy-data/energydata.info/files/2136860/Error.docx)

Thank you

Shaimaa

**Comment by jodiegardiner** [comment]
HI Shahmed.

This is because the data is in geojson format and is viewable in a browser.  If you would rather download the file, you can right-click on the button and choose "Save link as..."
