### ISSUE TITLE
Broken Sidebar Menu

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#236]
The sidebar menu does not work when the window is minimized on the site and when accessed using the phone. 
![f1](https://user-images.githubusercontent.com/36420556/42823589-e72070d6-89ab-11e8-8bd4-ea8bdbca14a5.JPG)
@TigranParvanyan @JemiTheKey

**Comment by jodiegardiner** [comment]
Thank you @shandaoz, I'll look at this soon.

**Comment by jodiegardiner** [comment]
Well, this was far more time consuming than it should have been in the end given the fix!  We got there though.  Fixed and viewable on staging, pushed in next deploy.

**Comment by shandaoz** [comment]
Thanks Jodie!

**Comment by shandaoz** [comment]
The side bar menu at the top of the page could not be expanded on the phone

**Comment by jodiegardiner** [comment]
FIxed and deployed to prod
