### ISSUE TITLE
No email pop-up when you click on authors 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#237]
Email does not pop up when you click on an author's contact information for any dataset.
![email pop up](https://user-images.githubusercontent.com/36420556/42966765-2765cee0-8b6c-11e8-8104-f88747165fbe.JPG)
@TigranParvanyan @JemiTheKey

**Comment by jodiegardiner** [comment]
What behaviour is expected here?

**Comment by shandaoz** [comment]
Supposedly when you click on an author's contact information, an email drafting box should pop up, with the author's email already written in the recipient's column. I also discovered that clicking on the email thumbnail in "connect us" no longer generates this behavior as well. 
![2](https://user-images.githubusercontent.com/36420556/43146198-be4e97fe-8f2e-11e8-9f47-2b5f21d06b51.JPG) 
![1](https://user-images.githubusercontent.com/36420556/43146018-3f71f7c8-8f2e-11e8-9511-48380494c967.JPG)
@TigranParvanyan @JemiTheKey

**Comment by jodiegardiner** [comment]
When I click on the author name, my email client opens with the address already filled in:

<img width="600" alt="screen shot 2018-07-24 at 15 50 12" src="https://user-images.githubusercontent.com/21362845/43146551-5b456856-8f59-11e8-8366-6f9c00d19628.png">

Have you changed mail settings or client lately perhaps?

I am using Google Chrome and Mac Mail.  What browser/mail_client combo are you using?

**Comment by shandaoz** [comment]
That's strange. I have not changed my setting recently. I use Google Chrome and Windows 10. We also tried clicking the contact information around using the Bank's lap tops (Chrome and Windows 10), but we were unable to get your results.

**Comment by jodiegardiner** [comment]
Hi folks.
I tested extensively using this tool:

https://www.browserstack.com/

I could not replicate the behaviour you mention.  I was able to test using Windows 10 and chrome (latest) and got the email client selection popup as expected.

Could you try the following and let me know how it goes please?:

- Open the Control Panel.
- In the Control Panel, search for Default Programs, then click it.
- Under Choose the programs that Windows uses by default, click Associate a file type or protocol with a program.
- Under Associate a file type or protocol with a program, scroll down the list until you find MAILTO.
- Double-click MAILTO, then choose the client you prefer.
- Click OK.
- Now try the mailto link again

**Comment by shandaoz** [comment]
Thanks Jodie!
