### ISSUE TITLE
Custom data field for the metadata cannot be displayed 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#239]
The following custom data field cannot be displayed on the metadata page when created for this dataset: https://energydata.info/dataset/zambia-solar-radiation-measurement-data-2015-2017 
![custom field](https://user-images.githubusercontent.com/36420556/44368996-be599800-a4a2-11e8-8c9f-5844e5195bfb.JPG)
@JemiTheKey @TigranParvanyan

**Comment by jodiegardiner** [comment]
I have fixed this on staging.  Will be deployed to production in the next update.
