### ISSUE TITLE
URGENT-ENERGYDATA.INFO platform crashed 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#240]
![image](https://user-images.githubusercontent.com/36420556/44795034-bd49fa00-ab77-11e8-9914-613f26df90eb.png)

**Comment by jodiegardiner** [comment]
Sorting this now.

**Comment by jodiegardiner** [comment]
If you need to keep working on the site, press advanced then you can visit the site anyway.  It's still there.

**Comment by shandaoz** [comment]
When I pressed advanced, it did not take me to the site, but I received the following message.

"Energydata.info usually uses encryption to protect your information. When Google Chrome tried to connect to energydata.info this time, this site sent back an unusual error credential. This may be because an attacker is trying to impersonate energydata.info, or the Wi-Fi login screen interrupts the connection. Please be assured that your information is still secure because Google Chrome has stopped connecting without any data exchange.

You are currently unable to access energydata.info because this site uses HSTS. Network errors and attacks are usually temporary, so this page may return to normal later."

**Comment by jodiegardiner** [comment]
Fixed

**Comment by shandaoz** [comment]
Thanks!
