### ISSUE TITLE
User Survey feedback

### ISSUE THREAD

**Issue by jodiegardiner** [energy-data/energydata.info#242]
Hi @shandaoz,
I have broken up the user survey somewhat so that each question now has a page of its own.  You can see in Survey Monkey that this is quite an intuitive and straightforward process to repeat for further questions.

I also updated the theme of the survey to be in line with the ENERGYDATA.INFO site.

If you are satisfied that my contribution to the user survey is complete, please close this ticket.

**Comment by shandaoz** [comment]
Hi Jodie,

I have created a new account yesterday to test the features on staging, but so far has not triggered the survey even though I clicked on a bunch of datasets that I have not clicked/tested. Therefore, I could not see how the survey is currently displayed.

I also can't seem to login to survey monkey, using User: wbgenergydata and Password: FullEnergized
![login details](https://user-images.githubusercontent.com/36420556/44859756-c2c04680-ac42-11e8-8920-c2d5852d9d0f.JPG)

**Comment by jodiegardiner** [comment]
Incorrect password. My mistake. Check your mail.

**Comment by shandaoz** [comment]
Got it! The display looks great in Survey Monkey! 

If the pop up survey is initiated the first time I  open up a page, how come I have not seen it on my new account? 
Will the survey be initiated each time a user comes back to ENERGYDATA and clicks on a dataset, or will the user only see the pop up on their very first visit ?

**Comment by jodiegardiner** [comment]
If you are using the same browser for both CKAN accounts then you won't see it pop up again.  You could try the same dataset in another browser.  

Currently every single visitor will see it so I didn't want to limit that to site users.

**Comment by shandaoz** [comment]
I see :)

1. Can the pop up survey be initiated more than once? For example, if a visitor lands on a dataset page for the first time and decided to closed the survey without responding, the visitor would never be able to take or see the pop up survey again. I wonder if we could initiate the survey randomly (for future visits or after spending 10 mins on the platform etc.) for visitors who did not respond to the survey the first time.

2. How can we change the text for the survey intro?
![survet text](https://user-images.githubusercontent.com/36420556/44862857-9cea7000-ac49-11e8-8b4c-3fe0c2dbaffa.JPG)

**Comment by jodiegardiner** [comment]
1. I checked in survey monkey and with pop-up collectors like this, it is limited to once per visitor.

For 2.  Yes, on the "collect responses" tab in Survey Monkey. You may have to press the "Back" button at the bottom left of that tab a couple of times to get to the layout designer section.

**Comment by shandaoz** [comment]
I see. Survey monkey is easy to use and has a simple display. 
What about other survey apps? If in the future we would like to have more than once pop ups, would it be easy to switch to another survey service? 

Thanks! I found the layout designer!

**Comment by jodiegardiner** [comment]
Yes I'm sure that would be possible if other survey providers allow that feature.

**Comment by shandaoz** [comment]
Pop-up survey is triggered every day/every other day. Please investigate the configuration for Survey Monkey and uncover the reason behind this behavior.

**Comment by jodiegardiner** [comment]
I spent a good deal of time tracking the information for this down.  According to the documentation, the popup will trigger once per browser session.  What this means is that in order to get the popup to appear again to the same user, the browser must be entirely closed (not just the tab) and reopened.  Once this has happened, then the user will see the pop up again the next time they visit a dataset page. 

This behaviour is not configurable.

Most visitors will therefore see the popup only once unless they come back after closing their browser (that could be the same day or a week later).  If you see the popup then don't close your browser for a week then you will not see it again until you do.
