### ISSUE TITLE
Add number of likes next to the like button

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#243]
![k](https://user-images.githubusercontent.com/36420556/45324591-92b75400-b51c-11e8-938a-48e31fe5734b.jpg)

**Comment by jodiegardiner** [comment]
This is complete.

**Comment by shandaoz** [comment]
Hi Jodie, the new like button is a great way to avoid using repetitive thumbs up symbols! But, it is not very obvious to the users that this is a clickable feature. Could you have the word "Like" in place of "+1" for the like button?
![capture](https://user-images.githubusercontent.com/36420556/45628373-7454d980-ba83-11e8-895c-f09889f28867.PNG)

**Comment by jodiegardiner** [comment]
Replaced the +1 with "Like".
