### ISSUE TITLE
Auto-remove year from dataset titles

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#245]

**Comment by jodiegardiner** [comment]
Plan:
Run a script to parse dataset titles in the database and remove any references to Year.   Going forward, if additional data from other years is added to the portal, it should be added as a resource within the dataset.

I'll run this tomorrow.

**Comment by jodiegardiner** [comment]
Had a first stab at this today.  Clearly it needs some refinement... (nothing happened).

**Comment by shandaoz** [comment]
You can rock this Jodie!  ᕦ(ò_óˇ)ᕤ

**Comment by jodiegardiner** [comment]
We did it!  Please review :)

**Comment by shandaoz** [comment]
Yay! Great work! 
I went through the list of datasets and all the dates are indeed removed! I also stumbled upon 2 types of weird cookies.
1. The "-" in the datasets title were also removed for about 1/3 of the datasets. 
![dates1](https://user-images.githubusercontent.com/36420556/46030116-c8476a00-c0e4-11e8-8a36-b22e9e3c46d1.PNG)
2. Some "()" and symbols in the parentheses that used to be the data remained.
![dates2](https://user-images.githubusercontent.com/36420556/46030301-486dcf80-c0e5-11e8-9088-7534169a9aae.PNG)
![dates3](https://user-images.githubusercontent.com/36420556/46030408-9aaef080-c0e5-11e8-8d42-bd15bb4c5c7e.PNG)

**Comment by jodiegardiner** [comment]
Yep, I expected the ampersands to remain, there shouldn't be too many of them and easier to manually clean those up.  The hyphens too, depending on how many there are as there will be several legitimate hyphens in titles too I expect?

I'll incorporate removing the parentheses too.

The Kenya ones are interesting though, no hyphen should have been removed there as the script wasn't looking for hyphens at all...  

Looking at that again now. I will copy over the production database to staging so I can test again.

**Comment by jodiegardiner** [comment]
A side effect of that will be we lose the test comments and likes but no harm done there.

**Comment by shandaoz** [comment]
Sounds good ;)  There are limited number of  ampersands and hyphens of where dates used to be, so we can clean it up in production.
 
There are a lot more datasets with hyphens removed, please look into that. It might be a bit annoying to add them back in one by one.

**Comment by jodiegardiner** [comment]
Good morning Shandao,

I've copied the latest production database over, collected the latest views stats and reran the titles script.  It looks better to me (the Kenya datasets have their hyphens!).  I also stripped out the parentheses where appropriate.

Can you have a look over it and let me know if you're happy with how it is now please?

**Comment by shandaoz** [comment]
Good afternoon Jodie,

Everything looks great! Great work!
