### ISSUE TITLE
Server traffic investigation

### ISSUE THREAD

**Issue by jodiegardiner** [energy-data/energydata.info#246]
We are seeing a lot of requests coming in to the server from a WBG IP address:
192.86.106.81

I ran a check at:

https://ipinfo.info/html/ip_checker.php for that IP and got an email address:

> Checking IP Address
> 
> IP Address: 192.86.106.81
> 
> Geolocation: US (United States), DC, District of Columbia, 20433 Washington - Google Maps
> 
> Reverse DNS Lookup
> 
> c0566a51.xip.worldbank.org
> 
> 2nd Level Domain: c0566a51.xip.worldbank.org
> 
> Top Level Domain: ORG (Organization)

From that report I got the email address of the network centre:

ncenter@worldbankgroup.org

The requests are infrequent but can clog up the site for hours and result in reduced perfomance, slower page loads/fail to load etc.

Can I email this address directly to inquire what the purpose of the activity might be and if it can be scaled back or spread out or would that need to come from an internal WBG team?

Thanks

**Comment by shandaoz** [comment]
Thank you for notifying us of this issue. We are not familiar with this address. Please email this address and find out the purpose of their requests.

**Comment by jodiegardiner** [comment]
Email sent to network center, we shall await a response.

**Comment by jodiegardiner** [comment]
Have not heard anything back (and haven't noticed excessive server traffic lately).  Closing for now and will reopen if we encounter this again.
