### ISSUE TITLE
Electrification Paths Application Page is Broken 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#254]
![1](https://user-images.githubusercontent.com/36420556/49252187-55fb4a80-f3f1-11e8-97d0-b769746fab4d.PNG)
![2](https://user-images.githubusercontent.com/36420556/49252190-58f63b00-f3f1-11e8-8e56-b82a566a28f6.PNG)

**Comment by jodiegardiner** [comment]
Hi @shandaoz , I have fixed the link now.  They changed the url of their github account and I had to track that down but the link works now.
