### ISSUE TITLE
Comment feature does not work

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#257]
The web page crashes when trying to respond to an existing comment made by a site visitor on ENERGYDATA.INFO for [this dataset](https://energydata.info/dataset/pakistan-wind-measurement-data).
![comment error](https://user-images.githubusercontent.com/36420556/50836956-7f7c8f80-1328-11e9-92a8-a1313c80daac.PNG)

**Comment by jodiegardiner** [comment]
Looking at this now

**Comment by jodiegardiner** [comment]
Fixed. And deployed to production.

Please confirm and close if happy.

**Comment by shandaoz** [comment]
Production site does not allow me to create a comment and denies access when responding to a comment. 
![error](https://user-images.githubusercontent.com/36420556/50976021-f185dd80-14bc-11e9-9581-99a5e5467507.PNG)
![access denied](https://user-images.githubusercontent.com/36420556/50976023-f3e83780-14bc-11e9-8404-95d1a3731a6d.PNG)

**Comment by jodiegardiner** [comment]
:'(  Works for me.  See inbox for notifications.

<img width="1028" alt="screenshot 2019-01-10 at 15 00 15" src="https://user-images.githubusercontent.com/21362845/50976682-7afed500-14e8-11e9-964b-fcf69e9b95ae.png">

**Comment by shandaoz** [comment]
It now works!
