### ISSUE TITLE
URGENT-Dataset approval feature not working 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#258]
There are 3 issues regarding this:

1. ENERGYDATA did not receive email notifications when datasets are submitted for approval. 
Example: we received 7 dataset submissions in December 2018, but received 0 email notifications from the ENERGYDATA inbox.
![pending](https://user-images.githubusercontent.com/36420556/50908490-d00eee00-13f7-11e9-9695-812ce7b64d1b.PNG)

2. When a dataset is approved, the approval email notification was not sent to the data publisher/author, but to the admin who approved it, in this case, me. 
![wrong users](https://user-images.githubusercontent.com/36420556/50908507-da30ec80-13f7-11e9-8ba8-8c90416ef3d8.PNG)

3. When the dataset approval feature was first created, a list of pending datasets are shown in the admin dashboard. The dashboard is now gone and the only way you can find pending dataset is to look for them by clicking into every 'organizations' page and look for them one by one. 
![dashboard](https://user-images.githubusercontent.com/36420556/50908621-149a8980-13f8-11e9-8868-c1044c1dcdb1.PNG)

@jodiegardiner @TigranParvanyan @JemiTheKey

**Comment by jodiegardiner** [comment]
Hmm, strange. Looking back I can see all those emails in my inbox (I get them sent there in addition to your team).  Let me investigate and get back to you.

**Comment by jodiegardiner** [comment]
Dashboard is still there, you just need to click on the speedometer icon to the right of your username in the header :)

**Comment by shandaoz** [comment]
Found it! Thanks Jodie!

**Comment by jodiegardiner** [comment]
The email in the settings to send to is "energydata@worldbankgroup.org"  Is this correct?  Is it possible that your mail client is marking them as spam and putting them in junk?  If I am receiving emails to jodie@derilinx.com using the same system it is very likely the email is being sent.

**Comment by shandaoz** [comment]
Yes, the email address is correct. The only email notification we received was about a new comment. I checked ENERGYDATA's spam and junk, but did not find any notifications from the platform. 
![email edi](https://user-images.githubusercontent.com/36420556/50909597-2f6dfd80-13fa-11e9-8a4e-2fa4da638dd4.PNG)

**Comment by jodiegardiner** [comment]
i've found the underlying issue with point 2.  Will have that fixed asap.  I will use a non-admin user on staging to create a new dataset, and I will add your personal email to the list of emails that should be notified.  This means, myself, you and the aforementioned team email should be alerted simultaneously. Then we can check to see who receives what and what the up to date junk folders say.

**Comment by shandaoz** [comment]
Sounds good!

**Comment by jodiegardiner** [comment]
Hi @shandaoz 

I have performed that test now and see the notification in my inbox.  Did you get one?

I have also fixed the issue 2 and now the correct  user will be notified rather than the admin who approves.

All on staging at the moment.

I also see log messages indicating mail was successfully sent:

**Comment by jodiegardiner** [comment]
> INFO:ckan.lib.mailer:Sent email to jodie@derilinx.com
ckan_1                               | INFO:ckanext.pending_datasets.logic.action:Successfully notified official jodie@derilinx.com for dataset comment 6f45f655-7283-40d7-8644-b8f921e8ea33
ckan_1                               | INFO:ckan.lib.mailer:Sent email to energydata@worldbankgroup.org
ckan_1                               | INFO:ckanext.pending_datasets.logic.action:Successfully notified official energydata@worldbankgroup.org for dataset comment 6f45f655-7283-40d7-8644-b8f921e8ea33
ckan_1                               | INFO:ckan.lib.mailer:Sent email to szhou6@worldbank.org
ckan_1                               | INFO:ckanext.pending_datasets.logic.action:Successfully notified official szhou6@worldbank.org for dataset comment 6f45f655-7283-40d7-8644-b8f921e8ea33

**Comment by shandaoz** [comment]
I have received the notification email : "The following dataset, testing-notification-emails, was submitted on 2019-01-09 16:20 by derilinx_user and is pending approval."
Since I did not see a dataset for approval, did you receive and email notifying yourself that the dataset is approved?

**Comment by jodiegardiner** [comment]
That's right yes, I instantly approved it to check.  I will create another now and let you approve it to check again.  Is that notification only in your personal email or do you also see it in the team inbox?

**Comment by shandaoz** [comment]
I see the notification both in my personal and team inbox. If you can see the approval notification then, this is good!

**Comment by jodiegardiner** [comment]
<img width="663" alt="screenshot 2019-01-09 at 16 33 28" src="https://user-images.githubusercontent.com/21362845/50913469-56452780-142c-11e9-981b-e53490a030e7.png">


Hooray!

**Comment by jodiegardiner** [comment]
I will push all these fixes live right away then.

**Comment by shandaoz** [comment]
Thanks Jodie! That would be fantastic. Let me know when this is pushed live and I will close this issue.

Could you also looking into [this issue](https://github.com/energy-data/energydata.info/issues/257)? We cannot respond to comments.
