### ISSUE TITLE
Link to ENERGYDATA leads to 404 error page 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#260]
If you copy-paste the following link in your browser https://energydata.info/api/action/datastore_search?resource_id=c412ca57-bbc8-4a57-9793-3e9a9d330fe6 (clicking on it does not work) you will find a long text that a WB tool, the Global Wind Atlas, uses to obtain data from energydata.info. However, there seems to be a corrupt link, leading to a 404 error page on energydata.info. The link obtained from the aforementioned text points to https://energydata.info/dataset/png---wind-measurement-data--2018-2019--, whilst it should actually point to https://energydata.info/dataset/png-wind-measurement-data. Can this be corrected?

**Comment by jodiegardiner** [comment]
Resolved this a while ago.  Discovered in the process there are a few more that are also broken.

**Comment by jodiegardiner** [comment]
This is resolved now.
