### ISSUE TITLE
Archive for Superseded Datasets 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#263]
The Afghanistan – Annual Average Wind Speed Data is featured as one of the most liked datasets on the homepage. However, it is long superseded by another dataset and is highly misleading for users. We have many more superseded datasets and we would like to revisit our earlier discussions on creating an archive or developing a way to label such datasets. Ideally, the archive would hide the outdated datasets from user search to avoid confusion, or group the outdated datasets together and label themselves individually as a superseded file with a link to its most up-to-date dataset. Please let us know timeline and how the archive can be developed. 
![popular datasets](https://user-images.githubusercontent.com/36420556/51544278-92fe1f00-1e2d-11e9-9162-8bc8dfc16736.PNG)
@TigranParvanyan @JemiTheKey @deirdrelee

**Comment by jodiegardiner** [comment]
It sounds like superseded data should be removed if avoiding confusion is the goal.  If we don’t want anyone to see it, then it shouldn’t be able to be seen!  CKAN has a way to do this already, of course.  What do you think?

**Comment by shandaoz** [comment]
The team wants to keep the superseded data on the platform to show transparency and that we are making improvements to datasets on ENERGYDATA. That is why we want a archive to put all the superseded data, to not mislead our users with the most recent data.

**Comment by jodiegardiner** [comment]
Ok, we can do that.  Let me have a talk with the team about the best approach.

**Comment by jodiegardiner** [comment]
Following on from email describing process, green light to develop this feature.

**Comment by jodiegardiner** [comment]
This is rdy to go to production
