### ISSUE TITLE
Harvested Author field indicates World Bank Group rather than the Author name  

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#265]
![harvested dataset](https://user-images.githubusercontent.com/36420556/52216496-55a18480-2864-11e9-9f72-c2675bb832bf.PNG)

**Comment by jodiegardiner** [comment]
I'll check to see what comes out of DDH in the author field currently.

**Comment by jodiegardiner** [comment]
Our harvester DID overwrite this for some datasets as you can see but going forward it will not.  These will need to be manually corrected, or at least correct values collated into a spreadsheet I can parse.
