### ISSUE TITLE
Home page search bar works differently from the search bar on datasets page

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#266]
Input in home page search bar and "Datasets" search bar show different results. It appears that if a search is inputted from the home page, the results are not ordered based on "relevance", even though it is labeled so.
 Search results from the homepage:
![11111](https://user-images.githubusercontent.com/36420556/53044482-2476a600-3459-11e9-903e-6d43706f3479.PNG)
 Search results from the datasets page:
![22222](https://user-images.githubusercontent.com/36420556/53044491-2a6c8700-3459-11e9-9454-69f31bae95a2.PNG)

**Comment by jodiegardiner** [comment]
Ugh, yes this is horrible isn't it?  It's a known issue in core ckan - sorting is not passed to the search results when the origin is not the dataset search bar.

I have fixed it on staging now and will deploy to prod OOH.
