### ISSUE TITLE
Clear multiple tag/search selections

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#271]
Currently, when users trying to clear multiple tag selections, they have to un-select the selection results individually. We would like to have a button that clears all the selections. 
![Clear](https://user-images.githubusercontent.com/36420556/54563697-41db5900-49a0-11e9-89e1-c82b24db80cc.PNG)

**Comment by jodiegardiner** [comment]
I have added a clear all button when there are filters applied.  Testable on staging.
