### ISSUE TITLE
Cannot select and compare multiple tags in the same section

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#272]
When you select a country from the "Countries" side bar, your next pool of countries selection is reduce to datasets with overlapping countries with your first selected country (examples are included below). Users should not be restricted to select and compare various countries.
 
![s1](https://user-images.githubusercontent.com/36420556/55966563-a5c30b80-5c46-11e9-87cf-a44c9a74d58a.PNG)
![s2](https://user-images.githubusercontent.com/36420556/55966567-a8bdfc00-5c46-11e9-8385-fddf0f3432cd.PNG)
![s3](https://user-images.githubusercontent.com/36420556/55966575-ab205600-5c46-11e9-9725-6bb476a78bd2.PNG)

**Comment by jodiegardiner** [comment]
Hi Shandao. This will be major development as it is absolutely not how filters are supposed to work.  Filters are meant to narrow search results.  Essentially, this is a new feature and will take me some time as I will have to rewrite a significant part of CKAN's code.

I'd say this is about a day of work to implement. I will update the ticket once it is done, but it will almost certainly not be this week.

**Comment by shandaoz** [comment]
Hi Jodie. I see. Somehow I thought it originally worked like that. Since we addressed this feature in our Progress Update Response document last week. I will close this thread.
