### ISSUE TITLE
Unpublishing datasets/ adding an unpublish button

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#274]
For published/approved datasets on the production site, I cannot unpublish datasets because the metadata field "State" is missing. It would be great to have an "unpublish" button rather than labeling the datasets for revision and raise confusions in the approval process. 
staging: 
![image](https://user-images.githubusercontent.com/36420556/56236623-10fe4a80-6058-11e9-915c-7bce9d3ec2bb.png)
production: 
![image](https://user-images.githubusercontent.com/36420556/56236646-1e1b3980-6058-11e9-95ea-71bd1e9f3bb2.png)

**Comment by jodiegardiner** [comment]
Hey  Shandao,

Deleting it or making it private isn't enough? What does "unpublish" mean in this context?

**Comment by shandaoz** [comment]
Making it private (unpublish) would do, but how can I make a dataset private on ENERGYDATA?

**Comment by jodiegardiner** [comment]
Hey @shandaoz.  My colleague Swaroop has added this feature to staging. When you create or edit a dataset you can now set it as Private or Public (default is Public). This gives you a way to soft delete datasets (hide them from everyone without admin/editor access).  Effectively this is an "unpublish" feature.

If you are happy with it as it is, we can pull it to production shortly.

**Comment by shandaoz** [comment]
Hi Jodie! The Private setting works perfectly! Please push this to production. 

I understand that the platform is still under development and we are switching things around, but the static footer banner is half blocking selection buttons such as "Publish" and "Delete".

**Comment by jodiegardiner** [comment]
This feature is live now
