### ISSUE TITLE
Metadata form instructions and adjustments 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#277]
1. Add instructions for the title naming convention: "Country - Subject"(Example: Algeria - Power Plants) under metadata field, **Title**. Is it me or did we used to have the naming convention instructions underneath. 
![image](https://user-images.githubusercontent.com/36420556/56920659-cfc35d00-6a91-11e9-9bac-b3dbfae44a6d.png)
2. Add asterisk next to metadata field: **Author Email**
![image](https://user-images.githubusercontent.com/36420556/56920242-ba016800-6a90-11e9-8021-637d425a5737.png)
3. **Country** field selections are not in alphabetical order
![image](https://user-images.githubusercontent.com/36420556/56920944-8c1d2300-6a92-11e9-80e0-513962b12b49.png)

**Comment by jodiegardiner** [comment]
This has been implemented and is live on production.  Author email is no mandatory and there is now help text to advise on our naming convention.

https://energydata.info/dataset/new
