### ISSUE TITLE
Number of Views not Updated 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#278]
The number of views for datasets and organization are not updated. 
We have been clicking on the dataset below multiple times, but the number of views did not change.
![image](https://user-images.githubusercontent.com/36420556/57024607-01a80100-6c03-11e9-952d-df50b0ef5b96.png)

**Comment by jodiegardiner** [comment]
Just to update this - these numbers are being retained, they are just not yet making it to the UI yet.  No data has been lost.

**Comment by shandaoz** [comment]
Good to hear! When will the numbers be updated on the platform?

**Comment by jodiegardiner** [comment]
This is updating as expected now.

**Comment by shandaoz** [comment]
The number of views are not up-to-date. I noticed the number has stayed 48 for a couple of days so I gave the dataset a couple of clicks yesterday. Today the number remains the same as yesterday. 
![may20](https://user-images.githubusercontent.com/36420556/58121555-b36c9900-7bd5-11e9-8bfd-aac7cca32dc8.PNG)

**Comment by jodiegardiner** [comment]
Ugh, the process is completing as expected and is notifying me but I can see an error in the ckan logs. I'll fix it now and redeploy.

**Comment by jodiegardiner** [comment]
This process now runs daily
