### ISSUE TITLE
Embed function for maps - unable to copy code

### ISSUE THREAD

**Issue by ClaraIV** [energy-data/energydata.info#28]
Please see here: https://energydata.info/dataset/global-solar-stations-wbg-esmap/resource/3d76335d-d744-4e70-8384-f83d0a096422
I want to embed this map on a webpage, but the Embed button opens up a gray window that doesn't let me access any of the fields.

**Comment by olafveerman** [comment]
@ClaraIV just wanted to ping you. This was fixed and released to production:

![image](https://cloud.githubusercontent.com/assets/751330/20333749/b8cf7226-ab82-11e6-878b-49852b5a76c9.png)

cc @yanntanvez
