### ISSUE TITLE
SSL Verification fails when linked from data.worldbank.org

### ISSUE THREAD

**Issue by furnlound** [energy-data/energydata.info#282]
Hi!
I came across this site when applying for an STC position. Very interesting stuff here!

I noticed that when being directed to the portal from data.worldbank.org (e.g. [here](https://data.worldbank.org/topic/energy-and-mining#energyextractivesopendataplatform) ), you get a browser warning for ssl verification error. The problem is that the link is to [databox.worlbank.org](https://databox.worlbank.org) which is indeed CNAME'd to energydata.info, but the cert is only provided for energydata.info and www.energydata.info

Possible solution(s):
Conf nginx to supply cert for databox.worldbank.org, either via SAN or SNI, both supported by Letsencrypt.
or 
Update links to instead point to energydata.info

**Comment by jodiegardiner** [comment]
@shandaoz 

I believe the best solution for this is to have the data.worldbank.org links point to Energydata.info instead.  Not sure if that is Tim's team?

**Comment by shandaoz** [comment]
@furnlound Thanks for reporting this issue! The links have now been fixed.
