### ISSUE TITLE
URGENT: Broken Most Viewed Datasets Links 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#283]
![image](https://user-images.githubusercontent.com/36420556/58908741-61506b00-86df-11e9-8b00-653494bea79b.png)
 4 links on the homepage leads to Error 404s

**Comment by shandaoz** [comment]
@jodiegardiner

**Comment by jodiegardiner** [comment]
On an initial look, it seems someone or some process has changed a bunch of titles and that's broken the connection to the views database.

When I know more, you will.

**Comment by jodiegardiner** [comment]
For example, the previous url for Pakistan Solar data was:
https://energydata.info/dataset/pakistan-solar-measurement-wbg-esmap
There is an entry for this in the views table for this dataset.  

There is no entry in the views table for:
https://energydata.info/dataset/pakistan-solar-radiation-measurement-data-2014-2017
So it says 0 views.

**Comment by shandaoz** [comment]
That's odd. From the activity stream it only shows that it has not been touched by editors, but a bunch of Derilinx updates.

**Comment by jodiegardiner** [comment]
Yeah, it has come from the harvester.  So it has identified "updated" datasets by the last_modified date then updated production with the changes. So the names look to have been changed on DDH perhaps? I can fix this with a bit of manual work, and using the immutable identifier "id" instead of "name" in the views table.

**Comment by jodiegardiner** [comment]
Hi Shandao.  There are no longer any broken links in the Most Viewed box.  It's not 100% right yet as you can see if you click through to a dataset and see the views numbers there but it's significant progress.  I'm still working on an answer for what exactly happened.

**Comment by shandaoz** [comment]
Thanks Jodie!
One more thing: the titles of the datasets on the right are cut off. I know some of them have long titles, but the ones on the left are all displayed. Can the title displays be made consistent?
![image](https://user-images.githubusercontent.com/36420556/59036352-18162d80-883d-11e9-935b-b005d33aafd4.png)
