### ISSUE TITLE
Numbers of likes are missing on the homepage popular datasets section

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#285]
Homepage Popular datasets:
1. Numbers of likes are missing.
2. "Most viewed data" and "most liked" should be in the same row.
3. Centralize the "eye" icon. 
<img width="1050" alt="Screen Shot 2019-07-12 at 10 54 30 AM" src="https://user-images.githubusercontent.com/34387745/61138479-977aca80-a495-11e9-8247-d09beba65730.png">

**Comment by jodiegardiner** [comment]
Unexpected...  investigating now.

**Comment by jodiegardiner** [comment]
Fixed now.

**Comment by jodiegardiner** [comment]
Just noticed the other parts about alignment of icons. Doing that now...

**Comment by jodiegardiner** [comment]
OK, that's fixed now too.

**Comment by shandaoz** [comment]
woo hoo!
