### ISSUE TITLE
Zambia wind measurement data - broken link

### ISSUE THREAD

**Issue by deirdrelee** [energy-data/energydata.info#288]
https://energydata.info/dataset/zambia-wind-measurement-data

"Unfortunately, all links on the energydata.info webpage (https://energydata.info/dataset/zambia-wind-measurement-data) do not lead to any data / info, but only to the “404 Not found” page."

**Comment by ss-bhat** [comment]
Updated the dataset in staging:
https://energydata.staging.derilinx.com/dataset/zambia-wind-measurement-data

Thanks

**Comment by hy347mc** [comment]
> Updated the dataset in staging:
> https://energydata.staging.derilinx.com/dataset/zambia-wind-measurement-data
> 
> Thanks

Hi, when this can be fixed after updating in staging? Seems that our users still receive the '404 not found' page. Thanks

**Comment by deirdrelee** [comment]
If you approve these fixes on staging (i.e. if they look good to you), we will push the update to production.

**Comment by hy347mc** [comment]
> If you approve these fixes on staging (i.e. if they look good to you), we will push the update to production.

Hi Deirdre, thank you for your reply. Please push this update to production then. Thanks a lot!

**Comment by ss-bhat** [comment]
Pushed to prod. All links should be working now.

Please let me know if you face any issues. Thanks
