### ISSUE TITLE
Cleaning up test user accounts, groups, etc.

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/energydata.info#29]
I believe these were created by DevSeed. Could we please have all test users, groups, etc removed from the platform? Thanks!

![image](https://cloud.githubusercontent.com/assets/21108014/20013879/2fa1b9a0-a28b-11e6-8732-0fc687c51127.png)

**Comment by olafveerman** [comment]
These were created during the review process by OIS. I just cleaned everything.
