### ISSUE TITLE
Pakistan - wind measurement Data dataset were breaking

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#290]
DDH was running our harvester in STG, and noticed that the resources for the [Pakistan - Wind Measurement Data](https://energydata.info/api/3/action/package_show?id=520eb754-84de-45fb-8d2c-7b2eaa2f7b6e) dataset were breaking (i.e leading to 404 pages). 

DDH also noticed that under the url_type field datacatalog links were present, not sure why though since this dataset is appearing in the [eex_user_origin = True endpoint ](https://energydata.info/api/3/action/package_search?fq=eex_user_origin:True%20organization:world-bank-grou&rows=1000)

**Comment by ss-bhat** [comment]
Updated the dataset in staging:

https://energydata.staging.derilinx.com/dataset/520eb754-84de-45fb-8d2c-7b2eaa2f7b6e

Could you please verify? Thanks

**Comment by hy347mc** [comment]
> Updated the dataset in staging:
> 
> https://energydata.staging.derilinx.com/dataset/520eb754-84de-45fb-8d2c-7b2eaa2f7b6e
> 
> Could you please verify? Thanks

Hi there,
Verified. Could you please push this update to production? Thanks a lot!

**Comment by ss-bhat** [comment]
Pushed to prod. All links should be working now.

Please let me know if you face any issues. Thanks

**Comment by hy347mc** [comment]
> Pushed to prod. All links should be working now.
> 
> Please let me know if you face any issues. Thanks

Hi there, just verified and they are all working now. Thanks!
