### ISSUE TITLE
Cannot download on PNG - wind measurement data

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#292]
the download function for any document on this [webpage](https://energydata.info/dataset/png-wind-measurement-data) is not working

**Comment by ss-bhat** [comment]
Updated the dataset in staging - 

https://energydata.staging.derilinx.com/dataset/png-wind-measurement-data

All the resources are downloadable. Could you please verify this? Thanks

**Comment by hy347mc** [comment]
Just verified that all the resources are downloadable now. Thanks!

**Comment by hy347mc** [comment]
Hi, I can download all files through the link you shared with me, but I cannot download any files through this link https://energydata.info/dataset/png-wind-measurement-data 

What's the difference? 

Thanks!

**Comment by hy347mc** [comment]
> Updated the dataset in staging -
> 
> https://energydata.staging.derilinx.com/dataset/png-wind-measurement-data
> 
> All the resources are downloadable. Could you please verify this? Thanks

Hi there,

Verified that all the resources are downloadable. Could you please push this update to production? Thanks a lot!

**Comment by ss-bhat** [comment]
Pushed to prod. All links should be working now.

Please let me know if you face any issues. Thanks
