### ISSUE TITLE
solar measurement datasets for Lebanon and Nepal are not linked to Global Solar Atlas

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#293]
the solar measurement datasets for [Lebanon](https://energydata.info/dataset/lebanon-solar-radiation-measurements) and [Nepal](https://energydata.info/dataset/nepal-solar-measurement-wbg-esmap), they are not linked to the Global Solar Atlas

**Comment by Taabu** [comment]
Data from Lebanon and Nepal added to World - Solar Stations Inventory resource. will push to prod after tomorrow's call.

**Comment by Taabu** [comment]
The Global Solar index reads its data from this dataset: https://energydata.info/dataset/world-solar-stations-inventory-2017
The solar measurement datasets for Lebanon and Nepal are not linked to the Global Solar Atlas, as they are not included in this amalgamated dataset. They are separately uploaded here:
https://energydata.info/dataset/lebanon-solar-radiation-measurements
https://energydata.info/dataset/nepal-solar-radiation-measurement-data
We need to agree on a process of how new data is added to the amalgamated dataset. Is the data owner responsible for appending them to the inclusive dataset, or is there an automated process that Derilinx can put in place to append. Or should the Global Solar index read from multiple datasets, not just one amalgamated dataset?
This is similar issues to #293 and #297
Let’s discuss the process going forward in the call.
