### ISSUE TITLE
wind measurement data for Ethiopia and Nepal is not included in Global Wind Altas measurement station layer

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#294]
The wind measurement data for [Ethiopia](https://energydata.info/dataset/ethiopia-wind-measurement-data) and [Nepal](https://energydata.info/dataset/nepal-wind-measurement-data) is not included in the Global Wind Atlas measurement station layer. Can you update the data storage behind the api? Link: https://energydata.info/api/action/datastore_search?resource_id=c412ca57-bbc8-4a57-9793-3e9a9d330fe6

**Comment by Taabu** [comment]
Data from Nepal and Ethiopia added to World - Wind Masts Inventory resource. will push to prod after tomorrow's call.

**Comment by Taabu** [comment]
The Global Wind Atlas reads its data from this dataset: https://energydata.info/dataset/world-wind-masts-inventory-2017
The wind measurement datasets for Ethiopia and Nepal are not linked to the Global Wind Atlas, as they are not included in this amalgamated dataset. They are separately uploaded here:
https://energydata.info/dataset/ethiopia-wind-measurement-data
https://energydata.info/dataset/nepal-wind-measurement-data
We need to agree on a process of how new data is added to the amalgamated dataset. Is the data owner responsible for appending them to the inclusive dataset, or is there an automated process that Derilinx can put in place to append. Or should the Global Wind Atlas read from multiple datasets, not just one amalgamated dataset?
This is similar issues to #294 and #297
Let’s discuss the process going forward in the call.
