### ISSUE TITLE
Request to add this app on the ENERGYDATA.INFO App page

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#296]
The new partner/organization, Enerdata, requested to add their app on our ENERGYDATA.INFO App page. Please find the link, description, and screenshot attached here. 

**Link**: https://yearbook.enerdata.net
**Description**: Enerdata's Global Energy Statistical Yearbook gives access to  world data on the production, consumption and trade of oil, gas, coal, power and renewable energies, as well as CO2 emissions from fuel combustion. The information is available through an online interactive application, with an intuitive and user-friendly interface using tables, maps and graphs covering world regions and individual countries. The data can be freely exported in .xls files for more in-depth analysis.
**Screenshot of its interface**:
![yearbook-home](https://user-images.githubusercontent.com/34387745/63530251-166f1400-c4d4-11e9-8a48-a2e5b2580413.png)

**Comment by jodiegardiner** [comment]
This app has now been added to the App page.
