### ISSUE TITLE
incorrect mast coordinates in Vietnam 

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#297]
the current coordinates on ENERGYDATA.INFO for the windmasts in Vietnam are off (some by 300km). Attached is the correct coordinates. Please update the ENERGYDATA.INFO [page](https://energydata.info/api/action/datastore_search?resource_id=c412ca57-bbc8-4a57-9793-3e9a9d330fe6) from which the coordinates are read by other maps. 

[GWA3.0 - Validation - Vietnam - Mast coordinates - Geo WGS84.xlsx](https://github.com/energy-data/energydata.info/files/3530993/GWA3.0.-.Validation.-.Vietnam.-.Mast.coordinates.-.Geo.WGS84.xlsx)

**Comment by Taabu** [comment]
Fixed on staging, will push it to production on Monday once Jodie is back.

**Comment by Taabu** [comment]
We need to agree on a process of how this dataset is updated. If there are new/updated coordinates, should the data owner directly replace/update the dataset at https://energydata.info/dataset/world-wind-masts-inventory-2017, or should the data be shared with Derilinx to update the dataset? For tighter data governance, we recommend the data owner updates the dataset.
This is similar issues to #293 and #294
Let’s discuss the process going forward in the call.
