### ISSUE TITLE
add: Mexico - Urban Performance/Metropolitan Profile Tool to ENERGYDATA App page

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#299]
Please add **Mexico - Urban Performance/Metropolitan Profile Tool** to ENERGYDATA App page

**link**: www.urbanperformance.in 

**description**: Assess the impact of urban policies and projects in future energy consumption levels at city scale and their implications in social, economic, and environmental aspects.

**image of the interface**: 
<img width="1440" alt="Urban Performance" src="https://user-images.githubusercontent.com/34387745/63949595-a965fc00-ca48-11e9-9893-752a10d3fe95.png">

**Comment by jodiegardiner** [comment]
This app has now been added to the apps page.
