### ISSUE TITLE
Multiple users with same email address

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/energydata.info#3]
I have added a new member to an organization I am admin of (RISE) using email invitation and it seems that the we have 2 users with the same email:  sreejithks-9609 and sreejithks-5300. 

Ideally we should not allow the multiplication of profiles, and restrict one user per email. What do you think? Is this a technical issue?

Thanks and kind regards,
-Yann

![user issue](https://cloud.githubusercontent.com/assets/21108014/18587493/51c3fc1c-7bf0-11e6-91e1-faf5d8537ab6.JPG)

**Comment by olafveerman** [comment]
This is a feature of CKAN: http://docs.ckan.org/en/latest/user-guide.html#registering-and-logging-in, but we could write a plugin to allow each email to be used only once.

**Comment by yanntanvez** [comment]
Thanks Olaf - not sure I fully understand the pros and cons with allowing or restricting the number of users per email, nor how labor intensive is to implement this plug-in? Let's perhaps discuss further. Thanks!

**Comment by olafveerman** [comment]
At the moment, users can only login with their username. If we'd allow one user per email, they could also log in with their email address.

**Comment by yanntanvez** [comment]
Thanks - let's not change the core code.
