### ISSUE TITLE
GeoJson not previewing like expected

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/energydata.info#31]
![image](https://cloud.githubusercontent.com/assets/21108014/20013998/a1444708-a28b-11e6-9f93-3f34ebba0550.png)

**Comment by olafveerman** [comment]
To be previewed, GeoJSON files need to be uploaded in WGS84. If it can't be previewed on a map, the system shows the json in text mode.

I added the GeoJSON with the WHS84 here:
https://energydata.info/dataset/transmission-network-tanzania/resource/db0567dc-0556-4464-85ed-1810cdd95213

**Comment by yanntanvez** [comment]
Is there a way to have the WGS84 also being vizualized? Or does this mean we need to re-format data that has not been uploaded on WGS84?
Thanks,
-Yann

**Comment by olafveerman** [comment]
Currently there is no way to preview a GeoJSON file that is not in WGS84 or Web Mercator. `tippecanoe` - the underlying library that we use to generate the tiles - only supports [EPSG:4326 (WGS84) and EPSG:3857 (Web mercator)](https://github.com/mapbox/tippecanoe#zoom-levels-and-resolution)
