### ISSUE TITLE
Display of licensing information

### ISSUE THREAD

**Issue by jodiegardiner** [energy-data/energydata.info#310]
Find the most user-friendly way to display licensing information. (ex: whether it should be displayed in the metadata form or elsewhere on the page).

To discuss in call.

**Comment by hy347mc** [comment]
> Find the most user-friendly way to display licensing information. (ex: whether it should be displayed in the metadata form or elsewhere on the page).
> 
> To discuss in call.

Just a note to say that several users asked me to provide more information on the license, which is actually listed on the right side of the box. See below, is there a way to make it more visible by making the font larger or changing it into another color? Or can we adjust the wording to something like: "Click here for more information on License definition and additional information"?  

![Capture1](https://user-images.githubusercontent.com/34387745/64972629-9ab87b00-d877-11e9-8cc3-b1ec87df49a8.PNG)

**Comment by jodiegardiner** [comment]
Yes, that would  be no problem at all.  I'll make it more visible and change the text. I'll let you know here when I've done so and you can see if that looks better.

**Comment by jodiegardiner** [comment]
Hi @hy347mc,

I've made that change now - check it out by editing any dataset (on production).  I made the text larger, black in color, and changed the wording.  

Please review and close if satisfied.
