### ISSUE TITLE
 Change manual input of file formats to drop-down box for uploading data files

### ISSUE THREAD

**Issue by jodiegardiner** [energy-data/energydata.info#314]
Potential issue here: Dropdown will have to cover every  possible format. Not practical given the thousands of potential file formats?

Will discuss in call.

**Comment by jodiegardiner** [comment]
Hi @hy347mc,

I'm thinking about this one and I see an issue.  I'm concerned a list of all possible file formats will be HUGE (and ugly) and not very necessary given we operate usually with a smaller range of different formats. However, we can't just use a smaller selection because then if someone wants to upload a format we don't have on the list, then what then?

Currently the Format is a text-box which autocompletes as you type based on existing formats but still allowing the user to add new formats.  Can we just double check to see if that functionality isn't better than what is proposed based on my feedback here?

**Comment by hy347mc** [comment]
> Hi @hy347mc,
> 
> I'm thinking about this one and I see an issue. I'm concerned a list of all possible file formats will be HUGE (and ugly) and not very necessary given we operate usually with a smaller range of different formats. However, we can't just use a smaller selection because then if someone wants to upload a format we don't have on the list, then what then?
> 
> Currently the Format is a text-box which autocompletes as you type based on existing formats but still allowing the user to add new formats. Can we just double check to see if that functionality isn't better than what is proposed based on my feedback here?

Hi Jodie,

Point taken. However, the reason we came up with this change is that we thought this might help tidy the format sector up on the ENERGYDATA platform. 

For example, in the figure below, we have 3 "xlsx" file, 2 "geotiff" file, 1 "geopackage" which isn't really clear to users, 1 "map" which is not clear or can be substituted by other format names. Most importantly, even we currently provide this text-box which gives a lot of flexibility for users to type whatever format type there, we still have this "other" format which is the second most commonly used format. 

Then, why not provide a drop-down box or check box directly and include the option called "other"? In that case, we are hoping to avoid the different expression of the same format. What do you think? Any ideas? Open to suggestions!

![Capture](https://user-images.githubusercontent.com/34387745/64970957-d6057a80-d874-11e9-990c-ac913556e876.PNG)


Thank you.

**Comment by jodiegardiner** [comment]
Hi @hy347mc,

That makes a lot of sense. I'll implement it like that and we'll see how it looks.

**Comment by jodiegardiner** [comment]
Hi @hy347mc 

Having written down the ones which seem to matter, the list is:

['CSV', 'DOC', 'GeoJSON', 'GeoTIFF', 'HTML', 'JSON', 'KML', 'KMZ', 'Other', 'PDF', 'RAR', 'SHP', 'SHP ZIP', 'TIFF', 'XLS', 'XLSX', 'ZIP']

Therefore the dropdown list wouldn't be all that bad.  Do you have other formats you would like included?  (Perhaps you are anticipating some data in the future that is of a format not listed.

**Comment by hy347mc** [comment]
> Hi @hy347mc
> 
> Having written down the ones which seem to matter, the list is:
> 
> ['CSV', 'DOC', 'GeoJSON', 'GeoTIFF', 'HTML', 'JSON', 'KML', 'KMZ', 'Other', 'PDF', 'RAR', 'SHP', 'SHP ZIP', 'TIFF', 'XLS', 'XLSX', 'ZIP']
> 
> Therefore the dropdown list wouldn't be all that bad. Do you have other formats you would like included? (Perhaps you are anticipating some data in the future that is of a format not listed.

Hi Jodie,

Thank you! This looks good to me. Could you also please list all these options alphabetically? Just another question on this: would it be possible for us to add additional options later on?

**Comment by jodiegardiner** [comment]
That list is currently sorted by name A>Z.  I think "Other" would be best at the end though, what do you think?

And it would be possible to add more but only by getting us to do it on your behalf.

**Comment by hy347mc** [comment]
> That list is currently sorted by name A>Z. I think "Other" would be best at the end though, what do you think?
> 
> And it would be possible to add more but only by getting us to do it on your behalf.

Right, my fault! The " SHP ZIP" is a bit confusing because it is displayed in two lines from my view. Yes please, I agree with you that "Other" should be listed at the very end. 

Sounds great!

**Comment by jodiegardiner** [comment]
Hi @hy347mc,

This change is live now.  Looks great!  You can test by editing any resource (or adding a new one).

In the case of an edited dataset, the current format is prefilled (if it exists in the list).

**Comment by hy347mc** [comment]
> Hi @hy347mc,
> 
> This change is live now. Looks great! You can test by editing any resource (or adding a new one).
> 
> In the case of an edited dataset, the current format is prefilled (if it exists in the list).

Thanks Jodie! This feature looks looks really nicer and smoother to me now.
