### ISSUE TITLE
add an Admin on GitHub and Energydata platform

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#317]
I sent Ammara, our new project manager, an invitation to join the energy-data GitHub group as an Admin. But she didn't received any invitation or even a notice from her end. Did I do it wrong or something is still needed to be done from your end? 

Similarly, I added her on the Energydata platform under the world bank group as an Admin. But she doesn't have the features that I, as an admin, have still. Is there anything else I should do or something is needed to be done from your end? 

Thanks!

**Comment by jodiegardiner** [comment]
Just saw this now Hong.  

You could try sharing this link with Ammara:

https://github.com/energy-data/energydata.info/invitations

I can see a pending invitation for ashariq12. If that's Ammara then that link should be all she needs.

For the energydata platform, there are organisation admins and sysadmins. Org admins don't have the same privileges. Would you like me to add Ammara as a sysadmin?

**Comment by hy347mc** [comment]
> Just saw this now Hong.
> 
> You could try sharing this link with Ammara:
> 
> https://github.com/energy-data/energydata.info/invitations
> 
> I can see a pending invitation for ashariq12. If that's Ammara then that link should be all she needs.
> 
> For the energydata platform, there are organisation admins and sysadmins. Org admins don't have the same privileges. Would you like me to add Ammara as a sysadmin?

Hi Jodie,

No worries and thanks so much for letting me know! This is indeed very helpful. I will share this link to Ammara, and yes, could you please add Ammara as the sysadmin for the EnergyData platform? I saw Jemi, the previous project manager, is the sysadmin; so I think we should add Ammara as our sysadmin as well. 

Thank you!

**Comment by jodiegardiner** [comment]
Ok, great. I've added the ckan user "ashariq" as a system administrator now.
