### ISSUE TITLE
Make "Country" and "Region" required fields and add the information symbol in front of the rest of the explanations

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#319]
1. Please add the red star in front of both "Country" and "Region"; please also remove the red star in front of "publish date of source data" (which isn't captured in this screenshot but just a few lines below). 
2. Please apply the same size and color of the font on other explanations after each field. For example, I think it would be nicer to apply the size and color of the font you used on "Click here for more information on license definition and additional information." on "Select at least one country or region." for the same reason, i.g. visibility. What do you think? 
3. Do you think it would be more consistent if we also put the "i" (information symbol) in front of each explanation? 

![Capture3](https://user-images.githubusercontent.com/34387745/65054946-60fd7800-d93c-11e9-95cd-3120854f35aa.PNG)

**Comment by jodiegardiner** [comment]
Great suggestion! Implemented for all info fields and it looks good!
