### ISSUE TITLE
Preview of CSV dataset retunring error

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/energydata.info#32]
![image](https://cloud.githubusercontent.com/assets/21108014/20184170/c23abf7e-a735-11e6-92a1-ec89d34240a6.png)

**Comment by olafveerman** [comment]
@yanntanvez Can you provide a link to this page? Can't find it on the platform.

**Comment by yanntanvez** [comment]
Cannot find it either - will re-open new ticket if that happens again, thanks!
