### ISSUE TITLE
links from inside the wind measurement stations give 404

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#320]
We received a message from one of our users saying that they noticed that links from inside the wind measurements stations give 404's and these links are taken directly from the ENERGYDATA.INFO platform API.

![Capture](https://user-images.githubusercontent.com/34387745/65472251-733d5180-de27-11e9-8bd5-5911674378c2.PNG)

**Comment by jodiegardiner** [comment]
Will get this sorted Hong, thanks.

**Comment by hy347mc** [comment]
> Will get this sorted Hong, thanks.

Hi Jodie,

On top of the issue itself, could you also let us know why this happened and what can be done to avoid this happen again in the future? Thanks.

**Comment by jodiegardiner** [comment]
Hi Hong, I believe you spoke about this with Eric (and I briefly). This one has to go back to the app authors/maintainer right?

**Comment by hy347mc** [comment]
> Hi Hong, I believe you spoke about this with Eric (and I briefly). This one has to go back to the app authors/maintainer right?

Hi Jodie, I talked with Eric briefly about another issue with Global Solar Altas, not this one. Should I check this with the Global Wind Altas team on this one?

**Comment by jodiegardiner** [comment]
Hi @hy347mc,

Sorry for missing your reply here. Yes, this is an issue with the app itself. The same issue that is present in the Solar Atlas. The links are pointing to resources which no longer exist. The link destinations will need to be updated.
