### ISSUE TITLE
Provide feedback on AWS Requirements for Solar Forecasting App

### ISSUE THREAD

**Issue by deirdrelee** [energy-data/energydata.info#321]
https://docs.google.com/document/d/1jz1CeGKBhc3lem4bWjvSGsXl0JfmoVHG8VPopuhD4Ro/edit

**Comment by deirdrelee** [comment]
@deirdrelee Provide workplan and costing for Solar Forecasting app

**Comment by EricSoroos** [comment]
The Google doc is only the basic configuration for the S3 bucket, not the lambda function that they were referencing in their presentation.

**Comment by deirdrelee** [comment]
Feedback provided and AWS access granted
