### ISSUE TITLE
Solar Forecasting App: Update AWS policy

### ISSUE THREAD

**Issue by deirdrelee** [energy-data/energydata.info#329]
Update AWS policy for Solar Forecasting App, as requested by Yerey Nnergix

**Comment by deirdrelee** [comment]
Update sent to NNergix. Concerns about amount of permissions they have requested. Alternative options given to them

**Comment by jodiegardiner** [comment]
A way forward has been agreed in principle with nnergix and will now construct a deployment pipeline using the agreed parameters.
