### ISSUE TITLE
Mobile usability issues detected

### ISSUE THREAD

**Issue by jodiegardiner** [energy-data/energydata.info#332]
> Search Console has identified that your site is affected by 3 Mobile Usability issues:
> Top Issues
> The following issues were found on your site:
> Clickable elements too close together
> 
> Viewport not set
> 
> Text too small to read

Mobile issues like these will not be present in the new version of the site which is practically ready to go.

**Comment by hy347mc** [comment]
> > Search Console has identified that your site is affected by 3 Mobile Usability issues:
> > Top Issues
> > The following issues were found on your site:
> > Clickable elements too close together
> > Viewport not set
> > Text too small to read
> 
> Mobile issues like these will not be present in the new version of the site which is practically ready to go.

Thanks Jodie and good to know. We will follow-up with our Common person to see when we can launch the new website and hopefully, the mobile usability won't be an issue by then.
