### ISSUE TITLE
Add GEP to the APPs + Feature GEP on the homepage

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#333]
Hi Jodie,

There are two things:
1. We want to add GEP to our APP page. 
2. We want to feature GEP on our current Homepage, by removing the "Electrification Pathways" and substituting it with GEP.

You can find the following items that you might need for this request. Let me know if you need anything else. Thank you! 

1. Link to GEP's app: https://electrifynow.energydata.info
2. A one-sentence description of GEP: The Global Electrification Platform (GEP) is an open-access, open-resource, online platform that explores options for achieving universal electrification for the countries with greatest electrification deficits globally. 
3. A screenshot of GEP:
![GEP_Front_Page](https://user-images.githubusercontent.com/34387745/71022393-5d5dc680-20ce-11ea-8069-f22ab419cfd9.JPG)

**Comment by jodiegardiner** [comment]
Hi @hy347mc 

This is implemented now and live on the front page and apps page.
Looking good.

**Comment by hy347mc** [comment]
> Hi @hy347mc
> 
> This is implemented now and live on the front page and apps page.
> Looking good.

Thanks! 👍
