### ISSUE TITLE
Change the attribution for the GEP to ESMAP, The World Bank Group

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#334]
Change the attribution for the GEP to "ESMAP and the World Bank Group" on boh the APP page and the Homepage
<img width="580" alt="Screen Shot 2020-01-02 at 10 24 35 AM" src="https://user-images.githubusercontent.com/34387745/71674802-3cda7100-2d4a-11ea-9a1a-255fa6e2a1f5.png">
<img width="1204" alt="Screen Shot 2020-01-02 at 10 30 34 AM" src="https://user-images.githubusercontent.com/34387745/71675058-f9343700-2d4a-11ea-9007-9085d9a29c90.png">

**Comment by jodiegardiner** [comment]
Hi Hong, this is done now. :)
