### ISSUE TITLE
question: on harvesting between DDH and Energydata

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#337]
Imagine a colleague who published a dataset through DDH and tagged EnergyData on the metadata form on DDH. Will this dataset automatically appear on EnergyData platform? Or if the colleague wants this dataset to appear on EnergyData platform, s/he still needs to fill out the metadata form on EnergyData and upload the datasets again?

**Comment by jodiegardiner** [comment]
Hi Hong.

No, the default behaviour would be that the dataset is created and maintained automatically by the harvester process.

**Comment by hy347mc** [comment]
> Hi Hong.
> 
> No, the default behaviour would be that the dataset is created and maintained automatically by the harvester process.

Thank a lot Jodie! Understood now!
