### ISSUE TITLE
Feature GEP in the  "What's new" section on Homepage 

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#339]
Please feature GEP in the "What's new" section on the homepage. The title will be "ESMAP & World Bank Group - Global Electrification Platform (GEP)".

<img width="1277" alt="Screen Shot 2020-02-10 at 4 51 00 PM" src="https://user-images.githubusercontent.com/34387745/74193632-ae4cef80-4c25-11ea-8340-c2f0861135f7.png">

**Comment by EricSoroos** [comment]
This is deployed on the energydata.info home page: 
![image](https://user-images.githubusercontent.com/36156267/74670773-25483200-51aa-11ea-9280-55c7be499011.png)

**Comment by hy347mc** [comment]
> This is deployed on the energydata.info home page:
> ![image](https://user-images.githubusercontent.com/36156267/74670773-25483200-51aa-11ea-9280-55c7be499011.png)

Thanks a lot Eric!
