### ISSUE TITLE
Cannot preview the CSV files on countries' solar irradiation and PV power potential

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#340]
See below as an example, for the countries' solar irradiation and PV power potential datasets, a user reported such document cannot be previewed. Is this a problem from our side, or from GSA's (Global Solar Atlas)? Thanks!

<img width="1274" alt="Screen Shot 2020-02-11 at 2 40 22 PM" src="https://user-images.githubusercontent.com/34387745/74272414-908e9180-4cdc-11ea-8687-e3519a50b86a.png">

**Comment by EricSoroos** [comment]
The CSV resource for Afghanistan in the EnergyData CKAN points to a HTML single page app download page for several different resources, none of which are actually CSV anymore. I'd bet that this changed at the release of the Global Solar Atlas 2.0 (listed as 23-Oct-2019).

These files are pointing to a protected S3 bucket: https://worldbank-atlas.s3.amazonaws.com/download/Afghanistan/Afghanistan_GISdata_LTAym_YearlyMonthlyTotals_GlobalSolarAtlas-v2_AAIGRID.zip, https://worldbank-atlas.s3.amazonaws.com/download/Afghanistan/Afghanistan_DNI_mid-size-map_156x164mm-300dpi_v20191015.png

There are two options for these downloads:
* EnergyData.info can point to the download page as an HTML resource, which will preview in an iframe in the page. This isn't a terribly friendly view of the download page, nor does it distinguish between the different forms of data on the page -- the DNI, GHI, PVPotential, or the GIS data. 
![image](https://user-images.githubusercontent.com/36156267/74644279-59096480-5176-11ea-94eb-1546d25f0992.png)
* We can load individual resources/urls from the S3 bucket into EnergyData and link to them directly. This is better from the data usage and user interface povs.  This bucket is protected, so we'd need to add a signing key for downloading the resources from the bucket. This is done in the app by redirecting through a url on the API server, e.g.: https://api.globalsolaratlas.info/download/Afghanistan/Afghanistan_DNI_mid-size-map_156x164mm-300dpi_v20191015.png . We could either redirect through the same API server, or we could get our own AWS signing keys for this bucket.

**Comment by EricSoroos** [comment]
We should probably set up a call to discuss the options and requirements for getting these GSA resources connected to EnergyData.info again.

**Comment by hy347mc** [comment]
> We should probably set up a call to discuss the options and requirements for getting these GSA resources connected to EnergyData.info again.

Sounds great, Eric! I am sending out an email today to all relevant colleagues within GSA to see when we can discuss this asap.

**Comment by jodiegardiner** [comment]
Do we have any updates on this one?

**Comment by hy347mc** [comment]
> Do we have any updates on this one?

Please refer to an email I sent to you all on **March 4th**. We decided to mark all those datasets named "Solar irradiation and PV power potential maps" as obsolete and create a single page pointing to the GSA resource, with a detailed description provided by GSA.

Rachel and I are currently working on this; hopefully, we will get back to the Derilinx team by the end of this week or early next week.

**Comment by jodiegardiner** [comment]
Fantastic!
