### ISSUE TITLE
missing dataset called "Bangladesh - Multi-Tier Framework (MTF) Survey"

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#341]
I approved this dataset around three weeks ago, it was on the Energydata.info platform and all links worked well; but the dataset is no longer on the platform anymore. Please find out why and fix it asap.

**Comment by jodiegardiner** [comment]
Dataset was hidden. Find it here again:
https://energydata.info/dataset/bangladesh-multi-tier-framework-mtf-survey
