### ISSUE TITLE
Africa Electricity Grids Explorer is not working 

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#344]
No data/map at all, seems to be a CORS erros. http://africagrid.energydata.info

**Comment by jodiegardiner** [comment]
Hi @hy347mc,
I'm emailing Devseed on this one and cc'ing you in.

**Comment by hy347mc** [comment]
> Hi @hy347mc,
> I'm emailing Devseed on this one and cc'ing you in.

Sounds good, please do!

**Comment by jodiegardiner** [comment]
Working now @hy347mc 

Didn't need to email Dev Seed after all. I fixed some configuration on our end that was minutely different  from staging (where it worked just fine).

**Comment by hy347mc** [comment]
> Working now @hy347mc
> 
> Didn't need to email Dev Seed after all. I fixed some configuration on our end that was minutely different from staging (where it worked just fine).

Awesome work! Thanks Jodie!
