### ISSUE TITLE
The magnifying glass is on the second line

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#346]
Is there a way to make the page adjust itself automatically given to any type of laptop that the users are using? The magnifying glass is not on the same line with the search box in my 12-inch screen...I also would assume that the search box doesn't need to be that long.  

<img width="1280" alt="Screen Shot 2020-03-03 at 12 31 13 PM" src="https://user-images.githubusercontent.com/34387745/75803225-1a65d380-5d4c-11ea-8ca5-a071d5c9dea1.png">

**Comment by jodiegardiner** [comment]
Weird. But hopefully an easy fix.

**Comment by jodiegardiner** [comment]
On further investigation, this appears to be happening only in Safari. Working on fix.
