### ISSUE TITLE
Change the way of displaying apps on the App page

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#348]
To make the **App page** handier and more appealing, could you please:
1. List 3~4 apps in a row but also make sure each figure is still visible and clear;
2. Keep the **name of the app** and **the organization name(s)** under the figure; 
3. Hide the description of each App, only display it when users are clicking on the figure. To further explain what I mean here, see the example here https://www.esmap.org/staff. You only see the staff's introduction after clicking on their pics. Similarly, we only want to display the description when clicking on the figure. 
4. Put the "View App" together with description of the App; for example, you can add one sentence like "Click here to view the App. " after each description. By doing so, users can go and view the app after reading the description. 
<img width="1280" alt="Screen Shot 2020-03-17 at 5 08 15 PM" src="https://user-images.githubusercontent.com/34387745/76902765-14571300-6873-11ea-888e-93a967525033.png">

**Comment by jodiegardiner** [comment]
@hy347mc 

Think I understand what is required here. I'll implement this soon and report back here.
