### ISSUE TITLE
Change the way of displaying partners on the Partner page

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#349]
We also decided to do the similar thing to **Partner** page

1. List 3~4 **logos** in a row but also make sure each figure is still visible and clear;
2. Hide the **description of each organization**, only display the **logo**, the **full name of the organization**, and **the number of datasets and the number of views**. See those circled in red in the picture attached. 
3. Only display the description of the organization (circled in blue) when users are clicking on the logo. For example, you can add one sentence like "Click here to view datasets from XXX (name of this partner)." after each description.

<img width="1276" alt="Screen Shot 2020-03-25 at 5 40 57 PM" src="https://user-images.githubusercontent.com/34387745/77590305-cf129100-6ec3-11ea-9551-7bcc5edca93b.png">

**Comment by jodiegardiner** [comment]
demo version up for view on staging now with core functionality in place:

https://energydata.staging.derilinx.com/organization

**Comment by hy347mc** [comment]
> demo version up for view on staging now with core functionality in place:
> 
> https://energydata.staging.derilinx.com/organization

Hi Jodie, glad to hear from you. This is exactly what I meant. Just want to let you know that some of the logos from my view are not displayed (or not displayed completely). Hope these are just minor issues. 
<img width="1280" alt="Screen Shot 2020-03-31 at 9 12 41 AM" src="https://user-images.githubusercontent.com/34387745/78030647-6ba7b980-7330-11ea-8c02-58721bc9feb0.png">

**Comment by jodiegardiner** [comment]
Curious. Will have a closer look.

**Comment by jodiegardiner** [comment]
This is complete now. I've also updated the images to better align with one another. Please check and close if you are happy
