### ISSUE TITLE
Title of the Partner page

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#350]
Just noticed the name of this page (circled in red) is not **partner** but **organization**. Is it easier for us to change it to "partner" for a better consistency? I am worried that once we change this to partner, it will affect other links to datasets searched by organization/partner. 

<img width="1280" alt="Screen Shot 2020-03-25 at 5 35 36 PM" src="https://user-images.githubusercontent.com/34387745/77590399-01bc8980-6ec4-11ea-9593-19507d39283b.png">

**Comment by jodiegardiner** [comment]
Fixed on staging. Push to prod scheduled for later today.

**Comment by jodiegardiner** [comment]
Pushed to prod now.
