### ISSUE TITLE
Add World Resources Institute's App on App page

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#353]
Link: https://www.energyaccessexplorer.org/

**By WRI and partners**

Description: The Energy Access Explorer (EAE) is an online, open-source, interactive platform that enables clean energy entrepreneurs, energy planners, donors, and development-oriented institutions to identify areas (at 1 km2 resolution) where energy access can be expanded and linked to socio-economic development. EAE synthesizes several geospatial data on resource availability, environment, power infrastructure, demographics, social and productive uses of electricity, and finance services and allows users to carry out custom multi-criteria analysis on-the-fly.

Picture of Interface:
![EAE - screenshot](https://user-images.githubusercontent.com/34387745/78370388-92662a00-7594-11ea-94f2-d91bba46e4d5.png)

**Comment by jodiegardiner** [comment]
live now
