### ISSUE TITLE
Hide GSA Solar Irradiation datasets

### ISSUE THREAD

**Issue by jodiegardiner** [energy-data/energydata.info#354]
These are not to be searchable on energydata.

**Comment by jodiegardiner** [comment]
Hi  @hy347mc 

I've made the list of these private, therefore not searchable by the public. I didn't delete them as we may find it useful to have a reference of what was.

As an admin user, you'll still see them, with the "Private" label.

**Comment by hy347mc** [comment]
> Hi @hy347mc
> 
> I've made the list of these private, therefore not searchable by the public. I didn't delete them as we may find it useful to have a reference of what was.
> 
> As an admin user, you'll still see them, with the "Private" label.

Confirmed!
