### ISSUE TITLE
Add this ESMAP's App on our App page

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#355]
**Name**: Systematic Review Map

**Link**: https://esmap.github.io/evidencemap/fuel/

**Description**: The mapping tool is an open-access visual representation of datasheets created for all studies included for the systematic evidence evaluation of the drivers and barriers for the transition to Modern Energy Cooking Services (MECS). Studies are georeferenced by the location of the study area on the interactive map. Studies are color-coded according to the sector of interest and users can apply filters- different topics, periods of time, duration of the study, design of the study, etc.- to explore sub-sets of the evidence base of most interest to them. Datasheets can be viewed for each study selected by this process. The data include full bibliographic details of each study and data extracted from the studies according to an a priori, peer-reviewed Protocol, which forms part of the final report of the systematic evidence evaluation.

**Producers**: by ESMAP and The World Bank Group

**Screenshot of the Interface**:

![MECS_map_thumb](https://user-images.githubusercontent.com/34387745/80132925-6c67f000-856a-11ea-845c-458ec61d69b4.PNG)

**Comment by jodiegardiner** [comment]
live now
