### ISSUE TITLE
replace the cover page for "Global Tracking Framework" on the Application page

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#356]
<img width="559" alt="Screen Shot 2021-02-10 at 10 30 02 AM" src="https://user-images.githubusercontent.com/34387745/107554566-fb420980-6b8a-11eb-981f-5b699275b50a.png">

The current cover page for the "Global Tracking Framework" on the Application page is old, please replace it with a screenshot of the current webpage here: https://trackingsdg7.esmap.org/

**Comment by jodiegardiner** [comment]
Hi Hong, I have updated the app screenshot as requested:

https://energydata.info/apps

Please check and close if you are happy with it.

**Comment by hy347mc** [comment]
> Hi Hong, I have updated the app screenshot as requested:
> 
> https://energydata.info/apps
> 
> Please check and close if you are happy with it.

Hi Jodie, confirmed. And it looks good to me! Thanks a lot for such a quick response.
