### ISSUE TITLE
Africa Electricity Grids Explorer

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#357]
the link to this app is broken on energydata.

**Comment by jodiegardiner** [comment]
<img width="923" alt="Screenshot 2021-05-05 at 16 29 58" src="https://user-images.githubusercontent.com/21362845/117167488-34230080-adbf-11eb-988a-3190eaf8809e.png">

It's not this one is it @hy347mc? From the apps page. I don't see any other links to that app anywhere else.

**Comment by hy347mc** [comment]
Yes it is the one. it now looks like below.
<img width="1279" alt="Screen Shot 2021-05-05 at 11 39 05 AM" src="https://user-images.githubusercontent.com/34387745/117168833-856aca00-ad96-11eb-90b8-f83e69fa85da.png">

**Comment by jodiegardiner** [comment]
Hi Hong, this is resolved now.
