### ISSUE TITLE
Dataset Views appear incorrect

### ISSUE THREAD

**Issue by jodiegardiner** [energy-data/energydata.info#361]

**Comment by jodiegardiner** [comment]
Remove this extension and use _tracking to populate the templates with values for views

**Comment by anderspeders** [comment]
Any updates on this?

**Comment by jodiegardiner** [comment]
This has been live gathering tracking data for a while on the live site. I have promoted the UI changes to accompany this as well now. View figures are up to date, and tracked by CKAN, so doesn't interact with GA at all now.

The view stats will update once a day when a background task runs.

Do you think there is real value in doing a one-off addition of the previous view counts we have in the db from the old method or would you prefer it remains as now, and is only counting from when I added internal tracking a couple of weeks ago?

**Comment by jodiegardiner** [comment]
live on prod now
