### ISSUE TITLE
CKAN 2.9 Upgrade

### ISSUE THREAD

**Issue by jodiegardiner** [energy-data/energydata.info#363]
Check each unique extension for compatibility

**Comment by jodiegardiner** [comment]
2.8 > 2.9 is a major upgrade for CKAN for two primary reasons:
Goes from Python 2 to Python 3
Changes routing to flask from pylons

This means that every extension must be updated to the new way to do things, whilst also going through all the code looking for python3 incompatibilities.

- [x] core ckan
- [x] ckanext-extrafields
- [x] ckanext-offgridtheme
- [x] ckanext-s3resources
- [x] ckanext-ytp_comments* Remove
- [x] ckanext-dataset_views* Disable Likes
- [x] ckanext-archive_dataset
- [x] ckanext-harvest
- [x] ckanext-mvt
- [x] ckanext-pending_datasets
- [x] ckanext-datastore_cleanup

**Comment by anderspeders** [comment]
It looks like a lot of progress was achieved by January. Could you please provide a status on the remaining items @jodiegardiner? It would be great to see this update released.

**Comment by jodiegardiner** [comment]
Hi @anderspeders. Yes, this is in final testing now. We expect to be ready to deploy by the end of this week.

**Comment by anderspeders** [comment]
Hi @jodiegardiner, Please let us know how the testing has gone. It would be great if you could proceed to release the CKAN update.

**Comment by gclapp1** [comment]
## Visualization Plugin Updates for CKAN 2.9
- [ ] Data Explorer
- [ ] DataStore Grid
- [ ] DataStore Graph
- [ ] DataStore Map

**Comment by gclapp1** [comment]
Hi @jodiegardiner, just wanted to follow-up on the status of the 2.9 update.

**Comment by jodiegardiner** [comment]
superceded by #386
