### ISSUE TITLE
Pending datasets on sysadmin dashboard

### ISSUE THREAD

**Issue by gclapp1** [energy-data/energydata.info#365]
Currently, when a user submits a dataset for pending approval, the system emails energydata@worldbankgroup.org the following message : 

<img width="742" alt="Screen Shot 2022-12-19 at 1 51 16 PM" src="https://user-images.githubusercontent.com/57463392/208498507-cbad9fe5-18b8-48cb-bede-2a4ad7155515.png">

*unfortunately, no information about which organization this dataset lives under

and there is no reflection on the EDI dashboard or interface as to where the dataset lives

<img width="1356" alt="Screen Shot 2022-12-19 at 9 33 46 AM" src="https://user-images.githubusercontent.com/57463392/208498804-64149609-6f8f-478f-8cf9-03dc3203ef67.png">

I have to go into each individual organization and check pending datasets

**Comment by jodiegardiner** [comment]
What if the email contains a url that takes you to the dataset in question?

You'd arrive here:
<img width="1337" alt="Screenshot 2022-12-21 at 23 58 05" src="https://user-images.githubusercontent.com/21362845/209026088-58bfc064-ee94-4daa-a8cd-a36d94a47371.png">

Handy reminder box at the top.  Or the link could even go directly into the edit page where you can change the State field.

It should be possible to have a tab on the User Dashboard with all pending datasets you are permitted to see, that would be a bit more work.

**Comment by gclapp1** [comment]
Would it be possible/easier to add pending dataset requests to the sysadmin NewsFeed as something I'm "following"?

**Comment by jodiegardiner** [comment]
I added urls to the notification mails at least.

Putting a link to it in a more convenient place sounds like a good idea.

**Comment by jodiegardiner** [comment]
I added a tab to the user Dashboard for Pending Datasets now.  Much more convenient.
