### ISSUE TITLE
Maintenance: Harvester Updates

### ISSUE THREAD

**Issue by gclapp1** [energy-data/energydata.info#368]
1. Status page that shows the most recent harvester run, timestamped, total datasets, number that were updated and output of any errors encountered to live on EDI  as a stand alone page and could be checked to see status without having to wonder what the most recent activity is

2. Harvester updates to synchronize with DDH per issue #352 from Hong

**Comment by anderspeders** [comment]
Is there any updates here Jodie?

**Comment by jodiegardiner** [comment]
Superceded by #383
