### ISSUE TITLE
Energydata.info issue detection updates 

### ISSUE THREAD

**Issue by gclapp1** [energy-data/energydata.info#369]
Issues still being sent to Oliver Knight.
- Would be best to go to Anders, myself & derilinx

<img width="526" alt="Screen Shot 2023-01-03 at 11 48 03 AM" src="https://user-images.githubusercontent.com/57463392/210402408-c5d6905b-12e2-40bc-99ad-571ac964308d.png">

**Comment by jodiegardiner** [comment]
Oliver was the person who set up the account originally, and since we took over managing energydata.info I don't seem to have access to change the core contact email unfortunately.

I have "Requested Access" to admin credentials.

**Comment by jodiegardiner** [comment]
I haven't received any contact on this.

**Comment by jodiegardiner** [comment]
I went into the admin and removed a few people who no longer are involved with the team.

**Comment by gclapp1** [comment]
Thank you for addressing these, am I correct in interpreting that you now do have admin credentials for the site?

**Comment by jodiegardiner** [comment]
Not for GA, but yes for the Search Console. I don't know why that distinction exists. I had to use a gmail address to add you to search console and I took yours from the GA admin area. You have full access there. To add others, i will need gmail addresses, although you'll also be able to do that ofc.
