### ISSUE TITLE
Not all countries tagged appear in left country bar 

### ISSUE THREAD

**Issue by anderspeders** [energy-data/energydata.info#381]
Not all countries appear in the left country bar (see for example Maldives missing). This is when browsing in default mode without applying any other filters. 

![image](https://user-images.githubusercontent.com/1101585/223416197-b6ba7956-6333-4fa2-a9e1-69e1c816d3d2.png)

![image](https://user-images.githubusercontent.com/1101585/223416410-ad152f22-75da-41f0-b779-d0c1fd561b32.png)

**Comment by jodiegardiner** [comment]
How very strange. Investigating.

**Comment by anderspeders** [comment]
You will also note that countries when listed do not appear alphabetically once you go past the first letter: For example Burundi appears before Benin, and Ghana appears before Gambia. 

![image](https://user-images.githubusercontent.com/1101585/227020866-dc16c74e-4e33-4dc5-98b5-ed442e0ac0d8.png)

So there are mulitple issues with the country left filtering bar.

**Comment by anderspeders** [comment]
Please share an update on this issue with the country left bar.

**Comment by jodiegardiner** [comment]
Hi Anders,

This is a two-part issue.

One is that there are two different country files. This is from legacy and I am consolidating.

Two is that they are sorted by the three digit ISO3 codes which explains the odd ordering. I am changing that to sort by display name.

**Comment by jodiegardiner** [comment]
I have discovered another interesting issue:

If you search for Maldives, it does appear in the left menu once results have been returned:
<img width="1047" alt="Screenshot 2023-03-28 at 14 49 08" src="https://user-images.githubusercontent.com/21362845/228259312-8b5a647e-76d6-40d6-afe1-f0b4185f80ee.png">
<img width="345" alt="Screenshot 2023-03-28 at 14 49 24" src="https://user-images.githubusercontent.com/21362845/228259332-9f041f93-2f76-4f76-8354-fcf87ad8cd05.png">

**Comment by jodiegardiner** [comment]
I think "Show all countries" may not, in fact, be showing all, technically speaking.

**Comment by jodiegardiner** [comment]
Solved, finally. This was simply a default limit of 50. So only the top 50 by dataset count were making the grade. Of course, once you drill down and search for a term, then less than 50 matching countries could be surfaced, explaining why Maldives only appears when searched for.  The fix is to remove this limit.  Deploying to prod in the morning when I'm fresh.

Part 2 is just sorting so I'll include that too, then return to close this once deployed, so you have visibility on it.

**Comment by jodiegardiner** [comment]
Deployed to production.
