### ISSUE TITLE
Maintenance: Dataset Page- File Size Visibility

### ISSUE THREAD

**Issue by gclapp1** [energy-data/energydata.info#384]
Include dataset size (MB, GB) as part of file preview on dataset page

**Comment by jodiegardiner** [comment]
So a dataset is the container for a number of resources. Therefore datasets do not have size. On the dataset page, it lists all the resources available. Do you mean each Resource should show its filesize on the individual Resource page?

**Comment by jodiegardiner** [comment]
e.g. https://energydata.info/dataset/congo-brazzaville-electrification-status-major-cities-2019/resource/85d685f2-9825-4e21-959e-26a3b8f05f5b

It's buried down in the Additional Info. We could potentially surface it up to the dataset page and put it on the Resource item tiles?

**Comment by jodiegardiner** [comment]
Where the size is available, we now show it in the resource item on the dataset page, e.g.
https://energydata.info/dataset/congo-brazzaville-electrification-status-major-cities-2019
