### ISSUE TITLE
Maintenance: Dataset Page- Hyperlink Topic Tags

### ISSUE THREAD

**Issue by gclapp1** [energy-data/energydata.info#385]
On dataset page, topic's should be linked i.e clicking "Solar" from a Solar Measurement Dataset page would take you back to the search interface for all datasets containing "Solar" as a topic

**Comment by jodiegardiner** [comment]
<img width="842" alt="Screenshot 2023-05-02 at 09 48 58" src="https://user-images.githubusercontent.com/21362845/235621820-c1fbb536-c97e-4263-a38b-21619389f108.png">

All done.
