### ISSUE TITLE
Maintenance: CKAN 2.9 Upgrade

### ISSUE THREAD

**Issue by gclapp1** [energy-data/energydata.info#386]
## From Issue #363
- [x]  core ckan
- [x]  ckanext-extrafields
- [x]  ckanext-offgridtheme
- [x]  ckanext-s3resources
- [x]  ckanext-ytp_comments* Remove
- [x]  ckanext-dataset_views* Disable Likes
- [x]  ckanext-archive_dataset
- [x]  ckanext-harvest
- [x]  ckanext-mvt
- [x]  ckanext-pending_datasets
- [x]  ckanext-datastore_cleanup

## Visualization Plugins
- [x] Data Explorer
- [x] DataStore Grid
- [x] DataStore Graph
- [x] DataStore Map

**Comment by anderspeders** [comment]
Do you have any updates here @jodiegardiner?

**Comment by jodiegardiner** [comment]
Hi Anders,

I’m just back this morning from vacation. I’ll find out imminently what progress there has been whilst I’ve been away.

Regards,

Jodie

**Comment by jodiegardiner** [comment]
Finally, I am deploying this today!

**Comment by jodiegardiner** [comment]
https://energydata.info/api/action/status_show

Ckan 2.9 installed on prod.
