### ISSUE TITLE
Embed function-code not working

### ISSUE THREAD

**Issue by ClaraIV** [energy-data/energydata.info#39]
I tried today to embed a map (https://energydata.info/dataset/global-solar-stations-wbg-esmap/resource/3d76335d-d744-4e70-8384-f83d0a096422) and nothing appears on the webpage.

**Comment by olafveerman** [comment]
@ClaraIV Can you point me to some code that explains how you're embedding the map?

**Comment by ClaraIV** [comment]
!DOCTYPE html>
<html>
<body>
<p class="rtejustify">The map below shows the locations of <strong>solar and wind measuring stations</strong> that have been installed under the above country projects, or previous initiatives where a partnership agreement exists. The full measurement will be made available for download at the end of October 2016.</p>
		<div>
			<iframe frameborder="0" height="400px" src="https://energydata.info/dataset/global-solar-stations-wbg-esmap/resource/3d76335d-d744-4e70-8384-f83d0a096422/view/08a94728-b884-4a39-85b0-7d5796bdc044" width="700px"></iframe></div>

</body>
</html>

**Comment by olafveerman** [comment]
@ClaraIV 
We can confirm this issue. This is caused by one of the security measures we had to take to prevent click-jacking.
We're looking into alternative solutions and post back here.
