### ISSUE TITLE
Dataset "Management" Page Showing Error

### ISSUE THREAD

**Issue by gclapp1** [energy-data/energydata.info#393]
Datasets are unable to be updated/"managed" and now show the following error when attempting to change regardless of what is in the "Author email" input:

![image](https://github.com/energy-data/energydata.info/assets/57463392/626dd429-0998-4b8b-9361-2bd5d162a6cb)

**Comment by jodiegardiner** [comment]
This doesn't seem to be happening for all datasets. It seems if it had a maintainer email before last week's update then it's fine. If it didn't, it's not. Maintainer and Maintainer Email are different fields than Author and Author Email and are hidden on the manage/new dataset form.

Proposed solution is simply to change validation so it doesn't care if it's missing or not.

**Comment by gclapp1** [comment]
That sounds fine, thank you Jodie

**Comment by jodiegardiner** [comment]
This has been resolved. Maintainer values are now ignored if empty or missing or null
