### ISSUE TITLE
SysAdmin Updates

### ISSUE THREAD

**Issue by gclapp1** [energy-data/energydata.info#394]
Please add Yi Wu (username: yiwu) as a sysadmin.

Please remove Hong Yang (username: hongyang) as a sysadmin.
Please remove Shandao Zhou (username: shandaoz) as a sysadmin

Thank you

**Comment by jodiegardiner** [comment]
@gclapp1 

Sure thing, that's no problem. Can you provide an email address as well please?

**Comment by gclapp1** [comment]
Sure, it should be ywu21@worldbank.org

**Comment by jodiegardiner** [comment]
That's done now. User yiwu added as Sysadmin and Hong removed.
