### ISSUE TITLE
Adding Rooftop Solar tile to application page

### ISSUE THREAD

**Issue by gclapp1** [energy-data/energydata.info#395]
It looks like rooftop solar has finally passed internal OIS testing and is sitting on the EDI domain at https://rooftopsolar.energydata.info/

We would appreciate if the application could be highlighted alongside the others on the "Apps" page.

For the summary blurb the team would like to use:
_"The rooftopsolar.energydata.info tool has developed a platform to showcase PV generation potential for each individual building rooftop in a given area, based on high resolution stereo satellite images using latest artificial intelligence techniques. Users can zoom in on rooftops or type in addresses to find a building(s) of interest.

The tool currently displays results from ESMAP's [15 pilot cities](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fenergydata.info.mcas.ms%2Forganization%2Fneo%3FMcasTsid%3D20893&McasCSRF=30fc01e8a0cc29de72146d8743b1655069b0a9af84f6b136d7210b9de7b95502) and will be adding results from every other city/area where similar analysis is being requested by World Bank regional task teams. Metrics such as suitable rooftop area for installation (m2), installable capacity (kW) and yearly potential (MWh) have been derived at individual building structure level and summed up to obtain the total potential for each city. The results can also be further aggregated for different building sectors (commercial, industrial, public, and residential)"_

And for the thumbnail we would like to use:
![image](https://github.com/energy-data/energydata.info/assets/57463392/1ecea9f6-1237-4c4f-9adf-080972377c96)

If following up by email would be helpful, happy to do so-trying to be more efficient in our asks.
Thanks!

**Comment by jodiegardiner** [comment]
https://ed4.staging.derilinx.com/apps

Here's how it looks on staging. I'll move it to prod later today and close this ticket when I have done so. I had to recreate the screenshot as they must be 1440 x 768 (or half/twice that).

**Comment by gclapp1** [comment]
Ah thank you, I'll make a note of that on our end for any future applications being transitioned onto EDI. Much appreciated

**Comment by jodiegardiner** [comment]
https://energydata.info/apps

Prod updated with the new app.

**Comment by gclapp1** [comment]
Thanks Jodie, looks great.

Only thing the team is asking for would be to make sure the attribution is to "NEO" (https://www.neo.nl/) and instead of "World Bank Group" we're supposed to just be using "World Bank" now

**Comment by jodiegardiner** [comment]
Changed attribution for the Rooftop app to NEO and changed all instances of "World Bank Group" to "World Bank".
