### ISSUE TITLE
Preview linked GeoJSON

### ISSUE THREAD

**Issue by olafveerman** [energy-data/energydata.info#40]
From #35 

> the GeoJSON resources pulled down from the federated site do not display in energydata.info because GeoJSON is set to read from our MVT extension. Should we have an alternative GeoJSON view for these resources?

**Comment by yanntanvez** [comment]
@olafveerman @kamicut - Could we please fix this relatively quickly? This is a problem for all of our Uganda datasets.

![image](https://cloud.githubusercontent.com/assets/21108014/21020924/6dfbd9aa-bd44-11e6-8fc8-cfd6ef14e4f0.png)

**Comment by yanntanvez** [comment]
A gentle reminder. Many thanks!

**Comment by olafveerman** [comment]
We just deployed a fix for this issue. External GeoJSON's will now be processed into Vector Tiles and displayed in the browser.

Example of a [GIZ geojson](https://energydata.info/dataset/distribution-substations-2016/resource/ae6cae24-b102-4da5-805c-4a21d8c317db):

![image](https://cloud.githubusercontent.com/assets/751330/21435818/c44affb0-c849-11e6-9428-647977f2b187.png)

This fix does not automatically generate a preview for the existing datasets. To kick off this process, one would have to 'edit the resource' and then hit 'update resource'.
