### ISSUE TITLE
Search by country - need to show all datasets for the country

### ISSUE THREAD

**Issue by kamicut** [energy-data/energydata.info#46]
Since the country codes are indexed instead of the country names (#44), searching for the country by name only works if the country name is in the description.

**Comment by carderne** [comment]
This still isn't fixed.

**Comment by jodiegardiner** [comment]
@shandaoz Is this still a relevant issue? Do you still see this behaviour?

**Comment by shandaoz** [comment]
@jodiegardiner Yes, this is still an issue. When you search the name of a country in the search bar, the number of datasets does not match the number in the countries side bar. Example below.
![country](https://user-images.githubusercontent.com/36420556/48571332-94164b80-e8d4-11e8-9c57-062a6f17d1df.PNG)
![nigeria](https://user-images.githubusercontent.com/36420556/48571334-94aee200-e8d4-11e8-803c-a278491d1f68.PNG)

**Comment by jodiegardiner** [comment]
As part of the work on the front page map for the new site version, I did some work on this issue  - although we currently still only find the resources specifically identified in the countries vocab during a search. There's a bit more development work to do to get this to do what we want.
