### ISSUE TITLE
New function: preview GeoTIFF

### ISSUE THREAD

**Issue by olafveerman** [energy-data/energydata.info#47]
- hosting; and
- preview

**Comment by jodiegardiner** [comment]
@shandaoz Is this still a relevant issue?

**Comment by shandaoz** [comment]
@jodiegardiner Yes, but in a slightly different way. I noticed that for some datasets there is a "+" displayed under the dataset title, when the number of countries exceeds 4. However, other datasets with more than 4 countries are all listed. Can we keep this display consistent to list a max of 3 countries with "+" behind for datasets with more than 3 countries?  
![number](https://user-images.githubusercontent.com/36420556/48571816-d12f0d80-e8d5-11e8-8a4d-883925823442.PNG)

**Comment by jodiegardiner** [comment]
Regions and Countries currently behave differently it seems. Would you like me to limit Regions to a max of 4?

**Comment by shandaoz** [comment]
Yes please!
