### ISSUE TITLE
Satellite basemap

### ISSUE THREAD

**Issue by kamicut** [energy-data/energydata.info#48]
cc @olafveerman

**Comment by olafveerman** [comment]
@yanntanvez will investigate if we need to integrate a basemap in particular

**Comment by olafveerman** [comment]
@yanntanvez

Do you have a preference between the light basemap:

![image](https://cloud.githubusercontent.com/assets/751330/21185051/278ac632-c1dd-11e6-8baa-1e6cc5b60af3.png)

or the colored:

![image](https://cloud.githubusercontent.com/assets/751330/21185084/442f9074-c1dd-11e6-91cb-ea6f938988a3.png)

**Comment by yanntanvez** [comment]
Hi Olaf,

The team and I discussed and we would love to have both if possible, with the white one being the primary and the ability to toggle to the colored one.

Thanks !

**Comment by yanntanvez** [comment]
Thanks for changing the base map already. I realize that the map we have is not really satellite and thus defeat the purpose of having it in the first place for users to check the validity of GIS datasets.

@olafveerman could we please therefore implement the following relatively quickly:
1. Stick to the initial plan with white map as default and ability to toggle towards the colored one.
2. if having two bases is not possible, then could we just have the white map only.

Thanks !

**Comment by olafveerman** [comment]
@yanntanvez 
We added the white baselayer and will be tackling the layer switcher soon. Work for that will be tracked here: https://github.com/developmentseed/ckanext-mvt/issues/3

**Comment by olafveerman** [comment]
This was implemented and deployed. We can always add extra / other mapbox layers at a later stage.
