### ISSUE TITLE
Set up monitoring for counting downloading times for each dataset

### ISSUE THREAD

**Issue by olafveerman** [energy-data/energydata.info#57]

**Comment by Naigege** [comment]
Look into getting stats on:

downloads
which apps people browse to

**Comment by jodiegardiner** [comment]
@shandaoz Is this still a relevant issue? This is a very vague specification.

**Comment by shandaoz** [comment]
@jodiegardiner They meant to set-up a monitoring system to track the number of downloads each dataset has. We agreed to track downloads from now on from our earlier calls. 
Just to double check, we do have a mechanism to track dataset downloads now correct?

**Comment by jodiegardiner** [comment]
No, that information is currently not tracked. Google Analytics doesn't do that by default so that requires development.

**Comment by shandaoz** [comment]
I will discuss this with the team and see if we want to proceed with this :)

**Comment by jodiegardiner** [comment]
duplicate of https://github.com/energy-data/energydata.info/issues/302
