### ISSUE TITLE
Add Organizations page

### ISSUE THREAD

**Issue by olafveerman** [energy-data/energydata.info#67]
By the end of the week:

- [x] linked from main menu
- [x] optimize layout. bit more space, more space for description
- [x] allow organizations not to be listed (`'list': false`)

**Comment by olafveerman** [comment]
Particular organizations can now be excluded from search results and the organization page. 
This is achieved by adding the organization id's that need to be ignored to the CKAN config in `.ini`:

`ckanext.theme.exclude_org_list = wbg`

@Naigege Where would you prefer to document this? Should we start using the Wiki functionality of GH?

**Comment by Naigege** [comment]
@olafveerman Sure. Please use what you think the best to document this. Thanks!

**Comment by olafveerman** [comment]
The organization page was deployed. Closing this issue until further feedback.
We also started a Wiki to capture the docs: https://github.com/energy-data/energydata.info/wiki/Energy-Data-admin-guide
