### ISSUE TITLE
Cannot preview geojson on chrome or safari browser

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#70]
System: macbook OS
Can preview the data on firefox only. 

One sample dataset link <https://energydata.info/dataset/kano-electricity-distribution-plc-kedco-mv-lines-2016/resource/1cc8fa80-49ba-4e66-b696-f99843a5f540> 

![image](https://cloud.githubusercontent.com/assets/6911487/21816209/4d0f2ec4-d72d-11e6-95d4-8da96e632b95.png)

**Comment by Naigege** [comment]
This issue may be more about the Mac OS. I could get the preview with chrome on windows machine.

**Comment by kamicut** [comment]
@Naigege Could you provide the version of Chrome (You can type `chrome://version` in the URL bar to get it) as well as macOS? 

It could be a problem with legacy WebGL (the technology we're using to run the preview). I have the latest version of Chrome and Safari and the preview is behaving as expected.

**Comment by Naigege** [comment]
@kamicut The chrome version: 55.0.2883.95 (Official Build) (64-bit)
MacOS: OS X 10.9.4
Safari version: Version 7.0.5 (9537.77.4)

You are right. The version on my macbook is quite out of date.

**Comment by kamicut** [comment]
@Naigege did updating your browser solve the issue?

**Comment by Naigege** [comment]
@kamicut Not really. Some GeoJSON files are still not previewed well, may be caused by the big data size? But for some very small GeoJSON dataset, preview does not work either: https://energydata.info/dataset/ghana-high-resolution-wind-resource-2003/resource/ce62e1c2-6d2a-46eb-8ab9-b9926ae30d47

Could you check it please? Thanks!

**Comment by kamicut** [comment]
@Naigege that preview file worked for me on Safari and Chrome. Is the version of Chrome you're running the same as the one linked above? 55.0 ?

**Comment by Naigege** [comment]
@kamicut I check my chrome, it is the most current version. 
<img width="409" alt="screenshot 2017-02-01 22 13 11" src="https://cloud.githubusercontent.com/assets/6911487/22535839/c8fa1b02-e8cb-11e6-9472-f7c4bc6b118d.png">

**Comment by Naigege** [comment]
@kamicut @olafveerman could you please prioritize this geojson preview fix, at least for the following datasets: 
https://energydata.info/dataset/liberia-cross-border-systems-clsg-proposed-grid-line/resource/534b3b9b-46d9-4655-9c86-31ca6e82dd00
https://energydata.info/dataset/liberia-maryland-nimba-grandgedeh-existing-grid-line
https://energydata.info/dataset/liberia-existing-grid-monrovia
https://energydata.info/dataset/liberia-populated-settlements

Please note this is an urgent request for these 4 datasets. Thanks a lot!

**Comment by olafveerman** [comment]
@Naigege 
Dataset 1, 2 and 4 are not in the proper projection. Geojson only supports WGS84 with lat/lon in decimal degrees. ([see the spec](https://tools.ietf.org/html/rfc7946#section-4))

What do you see in the case of the third dataset: https://energydata.info/dataset/liberia-existing-grid-monrovia/resource/9cc36728-3f58-45bb-8c63-a43dc7fd3792

**Comment by Naigege** [comment]
@olafveerman Could you add my account as platform administrator, please? So I can re-download those data, re-save to WGS84 and upload again. Please add me ASAP, so I can fix the projection. 

For the 3rd one, I can see the preview on windows system, but not on my personal macbook. But at least, it works on windows system. Thanks a lot!

**Comment by Naigege** [comment]
@kamicut when I upload a really big geojson (that is why you help me increase the size limit), the preview seems not working:
![image](https://cloud.githubusercontent.com/assets/6911487/22710282/be83e670-ed4a-11e6-97a4-5014e18355ae.png)

Is this caused by the too large file size? Is it possible to improve it? Thanks!

**Comment by Naigege** [comment]
Good for now. May revisit in future.
