### ISSUE TITLE
Review meta description and title

### ISSUE THREAD

**Issue by olafveerman** [energy-data/energydata.info#73]
That is included in search, Facebook + Twitter

**Comment by olafveerman** [comment]
@Naigege Can you have a look at the title and description we're proposing in: https://github.com/energy-data/energydata.info/pull/80
Let us know if you'd like to see any change.

**Comment by Naigege** [comment]
@olafveerman it looks good for me. Thanks!

@yanntanvez Is the description OK for you?

ckan.site_url = https://energydata.info
ckan.site_title = Energy Data
ckan.site_description = Open data and analytics for a sustainable energy future. Energy Data is an innovation of the World Bank Group.

**Comment by yanntanvez** [comment]
Thanks. A detail but let's please keep "energydata.info" instead of "Energy Data" for both title and description, so that it is consistent across platforms and communication messages.
Thanks!
