### ISSUE TITLE
Emphasize datasets on frontpage

### ISSUE THREAD

**Issue by olafveerman** [energy-data/energydata.info#75]
- move up in hierarchy (above App)
- make the list curated and manually updated:
  - 2 geospatial datasets with map preview
  - 1 non-geospatial dataset with a thumbnail as preview

Next step:

- decide which datasets to highlight @Naigege

**Comment by Naigege** [comment]
@olafveerman 
1st geospatial dataset: <https://energydata.info/dataset/ssa-aicd-electricity-transmission-network>

2nd geospatial dataset: <https://energydata.info/dataset/kano-electricity-distribution-plc-kedco-mv-lines-2016>

the non geospatial dataset: <https://energydata.info/dataset/making-power-affordable-for-africa-and-viable-for-its-utilities>
We can use the picture below as preview on front page: 
<img width="594" alt="screenshot 2017-01-10 22 04 04" src="https://cloud.githubusercontent.com/assets/6911487/21834384/a8f86caa-d782-11e6-9fd3-30acc4634c14.png">

**Comment by olafveerman** [comment]
Todo:

- [ ] @ricardomestre is developing the overall structure for this section
- [ ] @DylanMoriarty will take care of map styling for the two datasets

**Comment by olafveerman** [comment]
This was implemented and deployed.
@Naigege Feel free to re-open if you have questions / comments.

**Comment by Naigege** [comment]
@olafveerman Thanks! could you correct the size of picture on frontpage, please? It is not shown properly now: 

![image](https://cloud.githubusercontent.com/assets/6911487/22758331/3a861910-ee1c-11e6-9e2e-fb047617c4a9.png)

Thanks!

**Comment by Naigege** [comment]
@olafveerman The preview of emphasized dataset on front page is not viewed properly on the phone (tested on chrome and safari browser):
![image2](https://cloud.githubusercontent.com/assets/6911487/22791910/f02c0922-eeb8-11e6-926b-8ce4fbecadbe.PNG)
![image1](https://cloud.githubusercontent.com/assets/6911487/22791911/f03d94c6-eeb8-11e6-8ff9-0af4a7ef725a.PNG)

**Comment by ricardomestre** [comment]
@Naigege We've reworked the image to fit nicely within the datasets card layout:

![screen shot 2017-02-09 at 15 51 25](https://cloud.githubusercontent.com/assets/1016701/22791328/e8ab0aea-eee0-11e6-8bc2-88e8122ffedf.png)

For future reference, we are using images with a 16/10 ratio, prepared for retina screen (2x 512x320): **1024x640**.

**Comment by Naigege** [comment]
@ricardomestre Thanks! I add another preview error on smartphone browsers. Could you check it please?

**Comment by olafveerman** [comment]
@Naigege Thanks for reporting. Was able to replicate on iPhone, works well on Android.

**Comment by ricardomestre** [comment]
@Naigege It seems to be working on Android (Chrome). I'm trying to figure out what's going on iOS.

![16667508_10210794688675576_41165711_o](https://cloud.githubusercontent.com/assets/1016701/22793495/e8f563a4-eee7-11e6-959e-ab3eaae5a391.png)

**Comment by Naigege** [comment]
@ricardomestre Could you double check the image again, please? It is still not fitting well on my windows chrome, mac chrome & firefox. Thanks!  
![image](https://cloud.githubusercontent.com/assets/6911487/22798405/e837dfe0-eecf-11e6-85c2-5fba64d37ebe.png)

**Comment by olafveerman** [comment]
@Naigege 
Could you do a hard refresh and try again?
Closing this issue. Have opened a separate one for the iOS bug.

**Comment by Naigege** [comment]
@olafveerman The picture is right now. Thanks!
