### ISSUE TITLE
Reorganizing the Dataset Filtering bar

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/energydata.info#76]
Hi Team,

An issue I forgot to raise during the meeting... Could we please re-organize the bar on the left of the dataset section to better fit with our types of data. 

This would be in the following order:
1. Countries
2. Organizations
3. Groups
4. Tags
5. Formats
6. Licenses

Many thanks!

![capture - data platform](https://cloud.githubusercontent.com/assets/21108014/21830045/26c52170-d768-11e6-811a-47aba945cfaf.PNG)

**Comment by Naigege** [comment]
the new list:

1. Countries
2. Region
3. Topic
4. Organizations
5. Formats
6. Licenses

**Comment by olafveerman** [comment]
Add `published year` filter between region and topic.

**Comment by olafveerman** [comment]
The bar was reorganized.
