### ISSUE TITLE
Some data cannot be previewed regardless of browser and machine OS

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#78]
@olafveerman @kamicut Please check the examples blow:

https://energydata.info/dataset/distribution-lines-rea-proposed/resource/cd7da900-7bab-496b-ab59-31b168886034

https://energydata.info/dataset/transmission-substations-uetcl-proposed/resource/1ec67a5e-5694-400f-b893-f0d58d060b60

https://energydata.info/dataset/generation-sites-2016-operational/resource/c5fb893a-3fa7-4fb1-9f75-5c7ef3dc0cb2

**Comment by kamicut** [comment]
Thanks for reporting, there seems to be a javascript error on that page and I'll look into it.

**Comment by olafveerman** [comment]
@Naigege This should be resolved. Can you try again and let us know if it still doesn't work.

**Comment by Naigege** [comment]
@olafveerman I try again on a chrome Windows. It is still not working as below:

![image](https://cloud.githubusercontent.com/assets/6911487/22263083/30fd8298-e241-11e6-9016-8b17900b0a4d.png)
