### ISSUE TITLE
File upload failure b/c of large size

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#82]
@olafveerman @kamicut 
I tried to upload one geojson file with size of ~590MB, and I got the error as below. Is there a file size limit on the platform? Is it possible to enlarge the limit? 
![image](https://cloud.githubusercontent.com/assets/6911487/22226752/a478a16e-e195-11e6-9800-fd03a38e7c5d.png)

**Comment by Naigege** [comment]
Today I upload one zip file with 245MB, and it fails.

**Comment by kamicut** [comment]
@Naigege what do you think the max resource file size should be? I can increase it to 1GB for now.

**Comment by kamicut** [comment]
I increased the file size now to 1GB, could you try it again?

**Comment by Naigege** [comment]
@kamicut Could you increase the size to 1.5GB, please? Is it possible?

**Comment by kamicut** [comment]
@Naigege, we can definitely bump up the size but we have not tried the geospatial processing on this large of a dataset. If you'd prefer, we can make sure the processing will complete if you can provide us with the dataset before trying to upload it. Another strategy would be to chunk the dataset into multiple regions.

**Comment by Naigege** [comment]
@kamicut please find the geojson data at https://www.dropbox.com/s/3eyu69iiq5nsix2/ZAF_ACQ_DATE.geojson?dl=0

One thing I can do is compress this geojson file to make its size smaller than 1gb. Please let me know what is your opinion.

**Comment by kamicut** [comment]
@Naigege I tried doing the processing of the file locally and I think the system will be able to handle it if we increase the upload size to allow this file. As a quick check, the data in the file is a grid of polygons covering South Africa. 

![](https://kamicut-monosnap.s3.amazonaws.com/localhost30004.83-28.93728.745_2017-02-01_17-57-12.png)

![](https://kamicut-monosnap.s3.amazonaws.com/localhost30005.66-28.55125.601_2017-02-01_17-56-12.png)

Is this correct?

**Comment by Naigege** [comment]
@kamicut Correct! Thanks a lot!

**Comment by Naigege** [comment]
@kamicut I can still see the file too large error. Could you confirm the file size limit increase please?

![image](https://cloud.githubusercontent.com/assets/6911487/22655865/84dd2d6e-ec5f-11e6-9e32-ada8f84375b6.png)

**Comment by kamicut** [comment]
@Naigege I increased it to 2GB just now. Could you check again?

**Comment by Naigege** [comment]
@kamicut Yup. It is confirmed. Thanks a lot!

**Comment by Naigege** [comment]
Is the file size limit still 2GB? There is a user having trouble uploading 500MB file.

**Comment by kamicut** [comment]
@Naigege we've recently (#168) updated the geojson / vector tile processing code to have a configurable limit which we initially set to 500MB. We're trying to find a reasonable average limit which will balance the tile processing resource usage with the server resource usage to minimize downtime.

**Comment by olafveerman** [comment]
I just increased the size limit to 768MB. As @kamicut mentioned, we made this configurable and the trick will be finding a good limit that allows you to upload most files, while preserving resource usage.

This limit only applies to GeoJSON files. Other file types still have the 2GB limit.

cc @Naigege @carderne @JemiTheKey
