### ISSUE TITLE
Data API button missing & Preview problem

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#83]
@olafveerman 
One new dataset ( two csv files and one xlsx file) was uploaded this morning <https://energydata.info/dataset/global-solar-stations-wbg-esmap>. One of the csv file and xlsx file cannot be previewed and no **Data API** button: 
![image](https://cloud.githubusercontent.com/assets/6911487/22263987/6c4ba156-e244-11e6-8c7d-c7145e902ffd.png)

But the other csv file looks good:
![image](https://cloud.githubusercontent.com/assets/6911487/22264030/914f72e8-e244-11e6-90c4-e16eb99ef5ef.png)

Is this caused by the data file size? 
The data API button should be generated by CKAN for every dataset, right? 
Does preview feature has anything to do with Data API button? If the preview is not working, the Data API button is missing from what I observe.  

Here I see for this GeoJSON data, there is no DATA API button, even though preview works. 
![image](https://cloud.githubusercontent.com/assets/6911487/22264828/63eed87c-e247-11e6-8b59-5a5f7006bf41.png)

Thanks!

**Comment by Naigege** [comment]
The preview is OK, but no data API button <https://energydata.info/dataset/global-solar-stations-wbg-esmap/resource/204bb6d1-665c-4b9c-b3fa-3e9beb560316>

https://www.dropbox.com/s/i5wo4e1jhkeid9e/Screenshot%202017-02-20%2011.38.49.png?dl=0

**Comment by olafveerman** [comment]
Fixed: 
![image](https://cloud.githubusercontent.com/assets/751330/23867247/b146a526-07f1-11e7-908d-776ccda49143.png)

**Comment by Naigege** [comment]
@olafveerman The excel workbook is still not working even "upload to datastore" works https://energydata.info/dataset/global-solar-stations-wbg-esmap/resource/97e41748-2922-4ee7-a0e5-396eed540d19

![image](https://cloud.githubusercontent.com/assets/6911487/23880087/cc1f6b86-0827-11e7-80e5-06c9302032e3.png)

Thanks for double checking!
