### ISSUE TITLE
File not download, just open another browser tab  

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#86]
@olafveerman 
When I download a GeoJSON file from the platform, it directs me to a webpage as below. Usually, we should expect a file downloaded, not a webpage to visualize the json file. Could you check on it, please? Do not want to confuse the users by the "download" button. 

![image](https://cloud.githubusercontent.com/assets/6911487/22356413/31160a2e-e3ff-11e6-9cc7-e1daca126806.png)

**Comment by Naigege** [comment]
This issue is applied on downloading an csv file as well. Below shows a user feedback: 

1) BUG: Missing download parameter in HTML <a>-tag on energydata.info web page for both wind and solar, and biomass and everything else…:

There is a problem with the way the web pages are set up on energydata.info, surely not your fault, but you have to contact the IT crew who did these web pages…

I downloaded the data from the Maldives (now fortunately updated until the end of November 2017). And later I did some spotchecks on the Pakistan data.

The problem is that when I request to download any .csv file with wind data it does not really download to my desktop or download-folder as all other normal web sites would do it, but it opens it in a very ugly-looking web page. (In that case, I do not get the normal progress information on how far the download has proceeded, but I have to keep scrolling down the web page to see if there is more data coming in). Finally I have to save the web page data myself, even if I already demanded this download.

That is clearly a bug: 
The problem is that the download parameter is missing in the web page link’s <a> tag in HTML. In HTML5, this is how it is set up correctly (text copied from the w3schools basic web course!):

![image](https://user-images.githubusercontent.com/6911487/34582941-c64bae38-f163-11e7-8942-c48f100c2f90.png)

**Comment by jodiegardiner** [comment]
This has been implemented, you can see it in action on (amongst others) a geojson file here:

https://energydata.staging.derilinx.com/dataset/africa-water-bodies-2015/resource/5d6b9830-ed2c-43d4-90c4-0c53ca0591d1

**Comment by jodiegardiner** [comment]
Additionally, I also added this functionality to the main dataset page, so if you click "Go To Resource" then "Download" in the dropdown it will also correctly download.
