### ISSUE TITLE
Delete draft dataset

### ISSUE THREAD

**Issue by carderne** [energy-data/energydata.info#88]
I created a draft dataset: https://energydata.info/dataset/edit/test12312
It doesn't seem possible to delete it via the normal method?

Chris

**Comment by olafveerman** [comment]
@carderne 
Deleted datasets in CKAN are moved to a Trash where they're not visible to other users.
Admins can empty the trash on the following page: https://energydata.info/ckan-admin/trash

Please try it and let me know if you have any questions.

**Comment by carderne** [comment]
@olafveerman 

I understand that, but I had a draft dataset (not yet published), which I was not able to delete (although I'm sure I could just submit it and then delete it). Not a big issue so please don't prioritize it.

**Comment by olafveerman** [comment]
Ah, I misunderstood your initial issue. This is a known CKAN issue. You're required to create the dataset and then delete it.
