### ISSUE TITLE
Reorganize homepage

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#91]
@olafveerman 
Regarding the app display on front page, I would like to have 3 - 4 most used apps highlighted on the front page, and the rest sit in the app page, but there should be an organized and clean table only showing the rest app’s names and brief description on front page. What do you think?

**Comment by olafveerman** [comment]
@Naigege 

1. which apps do you want to highlight on the frontpage? With #90, we would have 5
2. do you still want to show the thumbnails for the apps on the frontpage?
3. the layout of the Apps page would remain the same?

**Comment by olafveerman** [comment]
As discussed in coordination meeting:

- reduce featured datasets to first two, side-by-side
- rename apps to latest apps
- keep only first two apps
- add link 'View all apps'

cc @Naigege @carderne
