### ISSUE TITLE
On iOS data is not loading for frontpage maps

### ISSUE THREAD

**Issue by olafveerman** [energy-data/energydata.info#99]
From [other issue](https://github.com/energy-data/energydata.info/issues/75#issuecomment-278689769), the data on the frontpage maps is not loading on iOS.

![image](https://cloud.githubusercontent.com/assets/751330/22798808/5e54f7a2-eed1-11e6-9f5d-ab73c544944a.png)

Same does not happen on Android.

**Comment by kamicut** [comment]
@DylanMoriarty by inspecting the web view in iOS safari, I found an error with loading 'fetch'

https://github.com/energy-data/energydata.info/blame/9075549f5e42757d776d01a8c5fee2f63fc902d4/ckanext-offgridtheme/ckanext/offgridtheme/templates/home/index.html#L33

fetch is [not available](http://caniuse.com/#search=fetch) for iOS and needs to be poly filled.
